### ISSUE TITLE
ZIO Test: Mock package variance annotation

### ISSUE THREAD

**Issue by saraiva132** [zio/zio#2540] opened 2019-12-30 11:49 UTC
**Goals**

I believe the mock package is lacking in terms of type variance. I was playing around with it for a while with the following results:

**Where?**

Files in question from package mock are: `ArgumentExpectation`, `Method` and `Expectation`. Increased correctness by adding contravariant and covariant notation where it made sense.

**Issue found?**

 The compiler can no longer infer types where contravariant notation now exists without type annotation in some tests.

**Test  example**

```
testSpec("||")(
        Module.singleParam(equalTo(10) || isWithin(1, 5)) returns valueF(input => s"foo $input"),
        Module.>.singleParam(3),
        equalTo("foo 3")
      )
    )
```

```
[error]zio/test-tests/shared/src/test/scala/zio/test/mock/ExpectationSpec.scala:266:80: type mismatch;
[error]  found   : Any* => String
[error]  required: Seq[Any] => String
[error]         Module.singleParam(equalTo(10) || isWithin(1, 5)) returns valueF(input => s"foo $input"),
[error]                                                                                ^
[info] Any* => String <: Seq[Any] => String?
[info] false
```

**What is the problem then?**

The compiler thinks `Any* => String <: Seq[Any] => String?` is not sound. Compiler is always right :D
 
This forces me to add types in all places that use methods from `mock.Expectation` object like `valueF`, `valueM`, `failureF` and `failureM`. Which is not what we want.

**Conclusion**

I wanted add variance correctness while keeping 100% type inference or at least, not make it worse. If this is not possible, I will need to give up for now.

Any ideas / techniques to try / evidences to give the compiler?

**Comment by adamgfraser** [comment] 2019-12-30 16:45
I think the issue is that when we make `I` contravariant we have to change the signature of `ArgumentExpectation.returns` from:

```scala
def returns[I, E, A](returns: ReturnExpectation[I, E, A]): Expectation[M, E, A]
```

to:

```scala
def returns[I1 <: I, E, A](returns: ReturnExpectation[I1, E, A]): Expectation[M, E, A]
```

This creates an issue when we call methods like `valueF`:

```scala
def valueF[I, A](f: I => A): ReturnExpectation[I, Nothing, A]

lazy val x: ArgumentExpectation[Any, Int, String] = ???
lazy val y: ReturnExpectation[Any, Nothing, String] = x.returns(i => i.toString)
// missing parameter type
```

Before, `I` was known to be `Int`. Now, `I` is only known to be a subtype of Int, which should be sufficient but the compiler wants the type of the input to the anonymous function to be fully known.

Note that this works correctly on Dotty. Example [here](https://scastie.scala-lang.org/6DuimR6sQDySumlQgHIHZA).

I don't really know how to solve this, though to be fair I'm also not sure this is actually a problem in that variance is always best practice but I am not aware of the lack of variance of this here causing issues for anyone.

It does look like variance annotations could be added to the other type parameters without issue.

**Comment by saraiva132** [comment] 2019-12-30 20:48
> Now, I is only known to be a subtype of Int, which should be sufficient but the compiler wants the type of the input to the anonymous function to be fully known.

This was my suspicion but you worded it very nicely. Thank you @adamgfraser

**Comment by adamgfraser** [comment] 2019-12-30 21:14
@saraiva132 You want to add variance annotations to the other type parameters and then we can close this?

**Comment by saraiva132** [comment] 2019-12-30 21:15
PR is incoming in a few minutes :)

**Closed** 2019-12-30 21:50 UTC
