### ISSUE TITLE
ZIO Test - no matching expectation with `forkDaemon`

### ISSUE THREAD

**Issue by renancaju** [zio/zio#3771] opened 2020-06-06 16:52 UTC
When using mocks with `forkDaemon`, a `no matching expectation error` occurs.

```scala
@accessible
object AModule {
  trait Service {
    def fa(a: Int): UIO[Int]
    def fb(b: Int): UIO[String]
  }
}

@mockable[AModule.Service]
object AMock

object TestSpec extends DefaultRunnableSpec {
  override def spec: ZSpec[zio.test.environment.TestEnvironment, Any] =
    suite("TestMockSpec")(
      testM("") {
        val aMock = {
          val a = AMock.Fa(
            equalTo(1),
            value(1)
          )
          val b = AMock.Fb(
            equalTo(2),
            value("2")
          )

          a andThen b
        }

        for {
          _ <- (AModule.fa(1).forkDaemon *> AModule.fb(2)).provideLayer(aMock)
        } yield assertCompletes
      }
    )
}
```
Output:

```
[info] - TestMockSpec
[info]   - 
[info]     - could not find a matching expectation
[info]       - invalid call to br.com.caju.authorizer.sandbox.AMock.Fb
[info]         expected br.com.caju.authorizer.sandbox.AMock.Fa with arguments equalTo(1)
```

**Comment by adamgfraser** [comment] 2020-06-08 17:53
Copying @ioleo.

Is this really a bug? If you are forking `fa` then `fb` is being executed concurrently with `fa`, which means `fb` could be executed before `fa`, violating the expectation.

**Comment by adamgfraser** [comment] 2020-06-12 18:13
@renancaju Did you get a chance to take a look at this? It seems like this is the expected behavior.

**Comment by renancaju** [comment] 2020-06-12 18:40
Hm, I actually didn't take a look at that yet, I was waiting for @ioleo to chip in. 

So if this is the expected behavior (i.e. the order is not guaranteed), is there a way to test the methods are called? It appears I'd have to use the `or` method with `andThen`, which brings us to https://github.com/zio/zio/issues/3769...

Are there any other ways?

**Comment by adamgfraser** [comment] 2020-06-12 19:14
So I think there are two things going on here, what is the expected behavior of the underlying method being tested and how should that behavior be verified.

In `a.fork *> b`, the order in which `a` and `b` are executed is indeterminate since once `a` is forked, execution of `a` and `b` is occurring concurrently on separate fibers so any order of execution is possible and the particular order of execution is dependent on the runtime.

In terms of how to test it, it looks like there is an `and` expectation distinct from `andThen` that allows you to test that two things happen regardless of the order. So I would try that.

Does that make sense?

**Comment by renancaju** [comment] 2020-06-12 20:42
I think it does make sense, but I'm not sure it would work every time. Here's another test case that you might be interested in. It has some of a random behavior.

```scala
import zio.test.DefaultRunnableSpec
import zio.test._
import zio.macros.accessible
import zio.test.mock.mockable
import zio.UIO
import zio.test.mock.Expectation._
import zio.test.Assertion._

@accessible
object AModule {
  trait Service {
    def fa(a: Int): UIO[Int]
  }
}

@accessible
object BModule {
  trait Service {
    def fb(a: Int): UIO[Int]
  }
}

@mockable[AModule.Service]
object AMock

@mockable[BModule.Service]
object BMock

object TestMockSpec extends DefaultRunnableSpec {

  override def spec =
    suite("TestMockSpec")(
      testM("") {
        checkM(Gen.anyUUID) { _ =>
          val aMock =
            AMock.Fa(
              equalTo(1),
              value(1)
            )

          val bMock =
            BMock.Fb(
              equalTo(2),
              value(2)
            )

          for {
            _ <- (AModule.fa(1) *> ZIO.effectTotal(println("executing...")) *> BModule.fb(2).forkDaemon).provideCustomLayer(aMock ++ bMock)
          } yield assertCompletes
        }
      }
    )

}

```

So, there are two modules now and I using both of them to create my layer. I use the `checkM` purely to create more tests runs. With the `println` you will see it fails after a few successful ones, so I'm guessing it has something to do with supervision of fibers, when the parent terminates, etc, but I'm no expert.

What would be the right way to test the calling of `BModule.fb`?

**Comment by adamgfraser** [comment] 2020-06-12 20:53
So why are you using forkDaemon there? By doing that you are creating a race condition because your effect will return immediately, possibly before fb has completed or even begun execution, in which case the expectation will not be satisfied. Why not just fa *> fa?

**Comment by renancaju** [comment] 2020-06-12 21:23
I'm working with some legacy code where I have to complete the request as fast as I can. The last step, which is not essential for the request to complete, but highly desirable to happen, is slow and needs to be `forkDaemon`ed in order for the request to complete in due time.

What happens in my production code is that the `forkDaemon`ed fiber outlives the main fiber. But that does not happen in the tests.

**Comment by adamgfraser** [comment] 2020-06-12 21:26
I don't think the issue is that the fiber doesn't outlive the main fiber but rather that the test framework evaluates whether the expectations were fulfilled when your effect completes and since you are forking this off to another fiber it may not have completed when the test framework evaluates whether the expectations were fulfilled. Can you use `zipPar` to do them both in parallel and wait for them to complete. It seems like you are going to need to wait for them to complete in your test in some way or the test is going to be flaky.

**Comment by renancaju** [comment] 2020-06-12 21:31
Got it. Unfortunately I can't use `zipPar` (the operation is REALLY slow, I can't afford to wait for it to complete in production). I believe the best approach here is to work on removing this dependency and live with a no-op implementation of the service that performs the slow operation in the specs. I guess mocks and forkDaemon are not meant to be used together, that's ok. Thanks for the explanation. 👍

**Comment by adamgfraser** [comment] 2020-06-12 21:33
Can you complete a promise from the slow service and wait on that in your test? I don't think it is an issue with `forkDaemon` as opposed to `fork` and I don't think it even has to do with the mocking framework. If you wanted to do any test for some condition being true you are going to need a way to wait for the effect that sets that condition to be true to complete.

**Comment by adamgfraser** [comment] 2020-06-13 01:44
Going to close this as I don't think there is an actionable item at this point. Feel free to reach out here or on Discord if there is anything else I can do to help with this.

**Closed by adamgfraser** 2020-06-13 01:44 UTC
Labels: bug, tests
