### ISSUE TITLE
Checklist: Make sure tests exist for all data types to be serializable

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1739] opened 2019-09-21 14:54 UTC

**Comment by jakubjanecek** [comment] 2019-09-21 17:21
I am taking this.

**Comment by jakubjanecek** [comment] 2019-09-21 18:36
- [x] Cause
- [x] Exit
- [x] FiberFailure
- [x] InterruptStatus
- [x] Promise
- [x] RefM
- [ ] ZSchedule

Tomas Herman is helping me and did others. We'll continue tomorrow.

**Comment by jakubjanecek** [comment] 2019-09-22 08:08
`RefM` is not serializable because it calls `fork` in `make`. This might be "fixed" in some future version.

**Comment by dkarlinsky** [comment] 2019-09-22 14:30
I've investigated the issue, where `ZTrace` deserialization fails with `java.lang.ClassNotFoundException: zio.internal.stacktracer.ZTraceElement$NoLocation`. 

The root cause is a class loader issue, which will probably not occur in normal application.
When deserializing, `ObjectInputStream` walks the stack to find the first "user class" (non java standard library class) and uses its class loader to load classes being deserialized.
Scala's `immutable.List` has custom serialization, so when deserializing anything held in a `List`, the first "user" class found down the stack is `scala.collection.immutable.List$SerializationProxy`, which is loaded by an SBT classloader that doesn't know any of the project classes, such as  `ZTraceElement$NoLocation`. Hence the `ClassNotFoundException`.
Not sure how this can be worked around...

**Comment by tomasherman** [comment] 2019-09-22 18:41
wow, good one

**Comment by ghostdogpr** [comment] 2019-09-22 19:14
We found a workaround (see the PR) 👏

**Comment by jakubjanecek** [comment] 2019-09-22 19:36
My jaw dropped 👏

**Comment by LGLO** [comment] 2019-09-22 20:08
Can we close it?

**Comment by ghostdogpr** [comment] 2019-09-22 20:11
Closed by #1771

**Closed by ghostdogpr** 2019-09-22 20:11 UTC
Labels: enhancement, good first issue, tests, zio-hackathon
