### ISSUE TITLE
ZStream FlatMap fails when used with groupedWithin

### ISSUE THREAD

**Issue by mindartur** [zio/zio#3780] opened 2020-06-08 08:27 UTC
```
import java.util.concurrent.TimeUnit

import org.scalatest.FunSuite
import zio.{RIO, Runtime, Task}
import zio.duration.Duration
import zio.stream.ZStream

class TestTimeMeasureZIO extends FunSuite {
  val runtime = Runtime.default

  test("test ZIO clock") {
    testFunction()
  }

  val numCores: Int = 1

  def testFunction(): Unit = {
    val stream = ZStream
      .fromIterable(Seq(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
      .groupedWithin(2, Duration(1, TimeUnit.SECONDS))
      .mapMPar(numCores)(someFlatMap(blockingEffect))
      .flatMap(y => ZStream.fromIterable(y.map(x => x * 2)))

    val result: List[Int] =
      runtime.unsafeRunTask(stream.runCollect)
    assert(result == List(2, 4, 6, 8, 10, 12, 14, 16, 18, 20))
  }

  def blockingEffect[F](x: F): Task[F] = Task {
    Thread.sleep(1000);
    x
  }

  def someFlatMap[I, O](func: I => Task[O]): I => RIO[Any, O] = {
    // Fails
    input: I =>
      for {
        result <- func(input)
      } yield result
  }

}
```

fails with 

```
[info] TestTimeMeasureZIO:
[info] - test ZIO clock *** FAILED ***
[info]   java.lang.InterruptedException: Interrupted by fibers: #1
[info]   at zio.Cause.$anonfun$squashWith$1(Cause.scala:405)
[info]   at scala.Option.orElse(Option.scala:306)
[info]   at zio.Cause.squashWith(Cause.scala:402)
[info]   at zio.Cause.squashWith$(Cause.scala:400)
[info]   at zio.Cause$Internal$Interrupt.squashWith(Cause.scala:748)
[info]   at zio.Cause.squashTraceWith(Cause.scala:427)
[info]   at zio.Cause.squashTraceWith$(Cause.scala:426)
[info]   at zio.Cause$Internal$Interrupt.squashTraceWith(Cause.scala:748)
[info]   at zio.Cause.squashTrace(Cause.scala:418)
[info]   at zio.Cause.squashTrace$(Cause.scala:417)
[info]   ...
[info]   Cause: zio.Cause$FiberTrace: Fiber failed.
[info] An interrupt was produced by #1.
[info] No ZIO Trace available.
[info]   ...
```

If I remove `groupedWithin` or `for {...} yield result` or `Thread.sleep(1000)` it works.

**Comment by mindartur** [comment] 2020-06-08 10:16
Following versions are used: 
```
"dev.zio" %% "zio" % "1.0.0-RC20",
"dev.zio" %% "zio-streams" % "1.0.0-RC20"
```

**Comment by iravid** [comment] 2020-06-08 19:57
Thanks for reporting @mindartur. Could you check this against the latest ZIO snapshot? There was a similar bug fixed in `aggregateAsyncWithin` (which underlies `groupedWithin`) recently.

**Comment by mindartur** [comment] 2020-06-09 09:12
@iravid it passes with latest `1.0.0-RC20+51-197673dc-SNAPSHOT`, thanks!

Does it make sense to add this test to the repo?

**Comment by iravid** [comment] 2020-06-09 18:15
@mindartur Sure why not. Feel free to send a PR.

**Comment by iravid** [comment] 2020-06-09 18:15
Oh well actually it may be hard to turn this into a testcase because of the use of thread blocking. If you can reproduce it without, that'd be great.

**Closed** 2020-06-15 15:26 UTC
Labels: bug, stream
