### ISSUE TITLE
high cpu usage after upgrading from zio 2.0.2 to 2.0.7

### ISSUE THREAD

**Issue by domdorn** [zio/zio#7801] opened 2023-02-08 13:58 UTC
I just upgraded a service that was still running zio 2.0.2 to 2.0.7 and seeing a strange change in cpu usage (memory usage got slightly better).. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/100349/217549577-d8714612-ac75-45c3-9969-0184df85a792.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/100349/217549665-13cc409d-df53-4b13-b1a2-b5703504e761.png)

The "main" functionality of this service is to serve work items from a database baked work queue that is using a zio semaphore to limit concurrent access.. could it be possible, that the changes related to racing might affect this? 

```scala
final private[core] case class GetNextCalcImpl(
  calcRepository: CalcRepositorySPI,
  heartbeatManager: HeartbeatManager,
  semaphore: Semaphore)
    extends GetNextCalc {

  private val maxTimeout     = 15.seconds
  private val shorterTimeout = maxTimeout.minus(1.second)
  private val retryInterval  = 1.second

  override def getNextCalc(
    correlationId: CorrelationId,
    worker: String,
    model: Optimierungsmodell): ZioF[Option[(JobId, CalcId, ProjectAttributes)]] = {
    val recordWorker = heartbeatManager.recordWorker(worker)
    val fetchAndUpdate = for {
      _ <- ZIO.unit
      // get a calculation from the repository.. maybe there or not (at this moment)
      maybeGetCalculation: ZIO[Any, Throwable, Option[CalcRepositorySPI.CalcData]] = calcRepository.getNextCalc(model)

      // move None to the error type
      calculationOrNone: ZIO[Any, Option[Throwable], CalcRepositorySPI.CalcData] = maybeGetCalculation.some

      // keep retrying in case of an "error" (No result or db failure) every second
      retryEverySecondToGetACalc: ZIO[Any, Option[Throwable], CalcRepositorySPI.CalcData] = calculationOrNone.retry(
        Schedule.fixed(retryInterval))

      // abort trying to get a calculation after 14 seconds. if we got a calc, success value is a Some, else None
      abortAfter14Seconds: ZIO[Any, Option[Throwable], Option[CalcRepositorySPI.CalcData]] = retryEverySecondToGetACalc
        .timeout(shorterTimeout)

      // flatten errors type
      withErrorHandling: ZIO[Any, Throwable, Option[CalcRepositorySPI.CalcData]] = abortAfter14Seconds
        .catchAll {
          // fail on a real exception
          case Some(e) => ZIO.fail(e)
          // or return None if there is simpy no calculation
          case None => ZIO.succeed(None)
        }

      maybeCalc <- withErrorHandling
      now       <- Timestamp.now

      // if we got a calculation by now, assign it to the client
      _ <- maybeCalc match {
        case Some(calc) => calcRepository.assignCalculation(correlationId, worker, calc.id, now)
        case None       => ZIO.unit
      }
    } yield maybeCalc.map(c => (c.jobId, c.id, c.data))

    recordWorker *> semaphore
      .withPermits(1)(fetchAndUpdate)
      // abort after maxTimeout seconds, so the connection to the calc-service gets closed as well.
      .timeout(maxTimeout)
      // we have an Option[Option[A]] now, so we flatten it.
      .map(_.flatten)
  }
```

**Comment by adamgfraser** [comment] 2023-02-08 20:57
@domdorn The change in the race semantics would if anything reduce CPU usage because you would be making sure that the connection was closed before continuing. There have been a lot of changes between 2.0.2 and 2.0.7 so I don't think any difference in performance can necessarily be attributed to changes in 2.0.7. If you can create a small reproducer can definitely take a look.

**Comment by jdegoes** [comment] 2023-02-09 10:55
@domdorn Are you doing a lot of `forkDaemon`?

**Comment by domdorn** [comment] 2023-02-09 11:55
@jdegoes no, I only have one forkDaemon in the whole microservice that looks like this:

```scala
object HeartbeatManagerImpl {
  val live: ZLayer[Any with Scope, Nothing, HeartbeatManager] = ZLayer.fromZIO(
    for {
      _ <- ZIO.debug("in creating heartbeatmanager")
      service <- ZIO.acquireRelease(for {
        _ <- ZIO.unit
        maps <- (for {
          workerMap   <- TMap.empty[String, Timestamp]
          jobMap      <- TMap.empty[JobId, Timestamp]
          calcMap     <- TMap.empty[CalcId, Timestamp]
          job2CalcMap <- TMap.empty[JobId, List[CalcId]]
        } yield (workerMap, jobMap, calcMap, job2CalcMap)).commit

        (workerMap, jobMap, calcMap, job2CalcMap) = maps
        fiberRef <- Ref.make[Option[Fiber.Runtime[_, _]]](None)
        srv = HeartbeatManagerImpl(workerMap, jobMap, calcMap, job2CalcMap, fiberRef)
        _ <- srv.start
        _ <- ZIO.debug("done starting heartbeatmanager")
      } yield srv)(srv =>
        (ZIO.debug("about to stop heartbeatmanager") *> srv.stop *> ZIO
          .debug("HeartbeatManager stopped")
          .ignore).ignoreLogged)
    } yield (service: HeartbeatManager)
  )
}

final private[core] case class HeartbeatManagerImpl(
  workerMap: TMap[String, Timestamp],
  jobMap: TMap[JobId, Timestamp],
  calcMap: TMap[CalcId, Timestamp],
  job2CalcMap: TMap[JobId, List[CalcId]],
  cleanupRef: zio.Ref[Option[Fiber.Runtime[_, _]]])
    extends HeartbeatManager {
  val workerPurgeTimeoutMillis      = workerPurgeTimeout.toMillis
  val calculationPurgeTimeoutMillis = calculationPurgeTimeout.toMillis

  def start: ZIO[Any, Nothing, Unit] = for {
    _ <- ZIO.unit
    _ <- ZIO.debug("starting HeartbeatManager")
    fiber <- (for {
      i <- zio.Clock.instant
      _ <- ZIO.debug("HeartbeatManager: periodic cleanup at " + i)
      _ <- cleanupWorker()
      _ <- cleanupJobsAndCalculations()
      _ <- ZIO.sleep(1.hour)
    } yield ()).forever.forkDaemon
    _ <- cleanupRef.set(Some(fiber))
    _ <- ZIO.debug("HeartbeatManager: Ref set")
  } yield ()

  def stop: ZIO[Any, Nothing, Unit] = for {
    _ <- cleanupRef.get.flatMap(ref => ref.map(_.interruptFork).getOrElse(ZIO.unit))
  } yield ()

```

**Comment by jdegoes** [comment] 2023-02-09 12:22
@domdorn Can you switch between the two versions in YourKit / JProfiler / VisualVM, and let us know what differences you see?

**Comment by domdorn** [comment] 2023-02-09 12:28
@jdegoes I can do that and capture recordings in YourKit. 
Unfortunately, I'm not an expert in YourKit, but I could provide you with the data captured so you could take a look?
Just tell me which recordings over which time span I should create.

**Comment by adamgfraser** [comment] 2023-02-09 13:45
@domdorn We also just released ZIO 2.0.8 with a couple of bug fixes. I don't think they are related to this but would be good to upgrade to make sure.

**Comment by domdorn** [comment] 2023-02-09 16:32
@adamgfraser looks like it didn't yet land in maven central, 
https://repo1.maven.org/maven2/dev/zio/zio_2.13/2.0.8 gives a 404

will try again tomorrow

**Comment by jdegoes** [comment] 2023-02-10 10:32
@domdorn 

Create a snapshot of CPU performance before and after, using the "Snapshot" feature. Then compare the snapshots and attach the result to this ticket.

See [here](https://www.yourkit.com/docs/java/help/cpu_compare_snapshots.jsp) for detailed instructions on how to generate the comparison.

Thank you for working with us on this! I owe you a beer at ZIO World. 😄

**Comment by hearnadam** [comment] 2023-04-26 00:46
Any update on this @domdorn? Would be good to root cause and resolve this issue.

**Comment by domdorn** [comment] 2023-04-26 08:59
Hi, 
I'm currently having a parental leave. Will be back in the office around May 20th and then have to see which tickets are to be done.. we definitely have some stability problems that are probably related to this issue. 
What I remember before going on leave is that it was also connected with garbage collection. 
Afaik John said something at ZIO World that improvements have been made in this area.

**Comment by adamgfraser** [comment] 2023-04-26 10:01
Yes this is an issue about 2.0.7 and we are on 2.0.13 at this point. I haven't seen any issues similar to this reported in a while so hopefully it has already been fixed but if not we can definitely look if we can reproduce it.

**Comment by guizmaii** [comment] 2024-12-17 06:11
@domdorn Can we close this issue?

**Comment by domdorn** [comment] 2024-12-17 10:13
yes, I haven't looked into it anymore and we're long past using those versions.

**Closed as completed** 2024-12-17 10:18 UTC
Labels: question, performance
