### ISSUE TITLE
`java.lang.StackOverflowError` in `ZTrace`

### ISSUE THREAD

**Issue by leobenkel** [zio/zio#3113] opened 2020-03-12 16:32 UTC
I encountered : 

```
java.lang.StackOverflowError
	at java.lang.Long.toString(Long.java:398)
	at java.lang.Long.toString(Long.java:1032)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at scala.StringContext.standardInterpolator(StringContext.scala:125)
	at scala.StringContext.s(StringContext.scala:95)
	at zio.ZTrace.prettyPrint(ZTrace.scala:33)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:46)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:45)
	at scala.Option.map(Option.scala:146)
	at zio.ZTrace.prettyPrint(ZTrace.scala:45)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:46)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:45)
	at scala.Option.map(Option.scala:146)
	at zio.ZTrace.prettyPrint(ZTrace.scala:45)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:46)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:45)
	at scala.Option.map(Option.scala:146)
	at zio.ZTrace.prettyPrint(ZTrace.scala:45)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:46)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:45)
	at scala.Option.map(Option.scala:146)
	at zio.ZTrace.prettyPrint(ZTrace.scala:45)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:46)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:45)
	at scala.Option.map(Option.scala:146)
	at zio.ZTrace.prettyPrint(ZTrace.scala:45)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:46)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:45)
...
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:45)
	at scala.Option.map(Option.scala:146)
	at zio.ZTrace.prettyPrint(ZTrace.scala:45)
	at zio.ZTrace$$anonfun$3.apply(ZTrace.scala:46)
```
in version `1.0.0-RC16`

**Comment by adamgfraser** [comment] 2020-03-12 16:34
If possible can you try upgrading to `1.0.0-RC18-2` and see if the issue is still present? Or if you have a minimized example we can check it on that.

**Comment by leobenkel** [comment] 2020-03-12 16:37
I got this exception as part of a large project in production. 
And since I didnt get the stack trace, I do not know what produced it :/ 
And since it is in production I cannot change the version in used at the moment :/ 
sorry.

**Comment by leobenkel** [comment] 2020-03-12 19:11
@adamgfraser I tried to update to `RC18` but the change in the Environment with the Layer is triggering a nightmare of changes that I cannot handle at the moment. Also, while searching for tutorial on how to convert the old to the new architecture, I saw post about `fork` being broken, which is a critical part of my application. So switching to `RC18` is out of the question right now.

**Comment by adamgfraser** [comment] 2020-03-12 19:24
@leobenkel Totally hear you about migrating. The issue with `fork` is only if you do `fork` inside of `zipWithPar`. As far as resources take a look at this [migration guide](https://docs.google.com/document/d/1P0mx1gSNU2UTi-9PXUeY8O74v5gyK-UETznM1SbkQjA/edit?usp=sharing) we put together. Totally understand waiting to upgrade, especially for an application you are using in production, but it also makes it hard to take action based on this ticket since a lot has changed since then, including several PRs to address stack safety with causes.

**Comment by leobenkel** [comment] 2020-03-12 19:31
ok, i will look at the migration guide and come back to you. Thanks !

**Comment by adamgfraser** [comment] 2021-12-24 03:02
Given the age of this issue and that I have not seen similar reports more recently going to close this.

**Closed by adamgfraser** 2021-12-24 03:02 UTC
