### ISSUE TITLE
I get unordered elements with Stream#mapMPar

### ISSUE THREAD

**Issue by mvillafuertem** [zio/zio#3470] opened 2020-04-27 13:43 UTC
Hi all, sometimes i get error with Stream#mapMPar . Any suggestion why this is happening? If I use a value higher than 16. For example 4096, the error is more frequently.

```scala
- App$ - 351 ms (100.00%)
  - StreamMapMPar
    List(1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 2) did not satisfy equalTo(List(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16))
  + StreamChunk - 351 ms (100.00%)
Ran 2 tests in 975 ms: 1 succeeded, 0 ignored, 1 failed
- App$
  - StreamMapMPar
    List(1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 2) did not satisfy equalTo(List(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16))

Process finished with exit code 1
```

```scala
object App extends DefaultRunnableSpec {


  def program(queue: Queue[Int]): Int => ZIO[Any, Nothing, Boolean] =
    i => queue.offer(i)
  override def spec: ZSpec[TestEnvironment, Any] =
    suite(getClass.getSimpleName)(
      testM("StreamMapMPar") {
        assertM(
          for {
            topic <- Queue.bounded[Int](16)
            a <- Stream.fromIterable(1 to 16).mapMPar(2)(program(topic)).runCollect
            elements <- Stream.fromQueue(topic).take(16).runCollect
          } yield elements
          // t h e n
        )(equalTo((1 to 16).toList))
      },
      testM("StreamChunk") {
        assertM(
          for {
            topic: Queue[Int] <- Queue.bounded[Int](16)
            _ <- ZStreamChunk
                  .fromChunks(Chunk.fromIterable(1 to 16))
                  .flattenChunks
                  .mapM(program(topic))
                  .runCollect
            elements <- Stream.fromQueue(topic).take(16).runCollect
          } yield elements
          // t h e n
        )(equalTo((1 to 16).toList))
      },
    ) @@ TestAspect.timed

}
```

Thanks

**Comment by narma** [comment] 2020-04-28 14:37
Well, `mapMPar` keeps the order of the results of the effects, but does not guarantee in which order the effects are executed.
Correct similar behaviour is 
```scala
case class TestMapMPar(size: Int) extends DefaultRunnableSpec {
  
    def program(queue: Queue[Int]): Int => ZIO[Any, Nothing, Boolean] = 
      i => queue.offer(i)
    override def spec: ZSpec[TestEnvironment, Any] =
      suite(getClass.getSimpleName)(
        testM("StreamMapMPar") {
          assertM(
            for {
              topic <- Queue.bounded[Int](size)
              a <- Stream.fromIterable(1 to size).mapMPar(2)(UIO.succeed(_)).tap(program(topic)).runCollect
              elements <- Stream.fromQueue(topic).take(size).runCollect
            } yield elements
            // t h e n
          )(equalTo((1 to size).toList))
        },
      ) @@ TestAspect.timed
  
  } 
```

**Comment by iravid** [comment] 2020-04-28 15:38
Ah that’s right. Thank you @narma for the diagnosis! Closing as this is not a bug.

**Closed** 2020-04-28 15:38 UTC
Labels: bug, stream

**Comment by mvillafuertem** [comment] 2020-05-01 12:51
Thank you @narma. I thought that when you use flatmap all this is synchronous and if you need parallel you have to use fork in your for comprehension, then this is not correct?
