### ISSUE TITLE
Dependency on sun.misc.SignalHandler causing NoClassDefFoundError

### ISSUE THREAD

**Issue by monktastic** [zio/zio#9240] opened 2024-10-10 21:29 UTC
I notice that ZIO [uses](https://github.com/zio/zio/blob/6362961efb3fe0af160b6b5e76b2a3014531825d/core/jvm/src/main/scala/zio/internal/PlatformSpecific.scala#L43) the deprecated `sun.misc.SignalHandler`:
```
  final def addSignalHandler(signal: String, action: () => Unit)(implicit unsafe: zio.Unsafe): Unit = {
    import sun.misc.Signal
    import sun.misc.SignalHandler
```

I'm building a plugin (written in ZIO) that conforms to the [Smithy](https://smithy.io/2.0/guides/smithy-build-json.html) plugin SPI, but when it's loaded by a Java 17 JVM and executed, it crashes:
```
Projection api-gw-transformer failed: java.lang.NoClassDefFoundError: sun/misc/SignalHandler
java.lang.NoClassDefFoundError: sun/misc/SignalHandler
	at zio.VersionSpecific.$init$(VersionSpecific.scala:78)
	at zio.package$.<clinit>(package.scala:24)
	at zio.ZLogger$.<clinit>(ZLogger.scala:108)
	at zio.RuntimePlatformSpecific.$init$(RuntimePlatformSpecific.scala:35)
	at zio.Runtime$.<clinit>(Runtime.scala:213)
```

The stack trace doesn't match, but I'm pretty sure the above code in `PlatformSpecific` is the problem.

All my plugin code does for now is:
```
    zio.Unsafe.unsafe { implicit u =>
      zio.Runtime.default.unsafe.run(ZIO.log("Test")).getOrThrowFiberFailure()
    }
```

I've even tried building with nearly the exact same version of Java (Corretto-17.0.12, whereas Smithy uses Corretto-17.0.12.7.1).

**Comment by monktastic** [comment] 2024-10-10 21:55
Actually, from more digging, it seems that the `java` bundled with Smithy might be the problem. It doesn't come with `sun.misc.Signal` etc.

**Comment by monktastic** [comment] 2024-10-11 02:42
I'll close for now. Although I don't think ZIO should have this dependency, it works on most JVMs.

**Comment by monktastic** [comment] 2024-10-11 02:42
I'll close for now. Although I don't think ZIO should have this dependency, it works on most JVMs.

**Comment by kyri-petrou** [comment] 2024-10-11 03:00
Hi @monktastic, I'm fairly certain that ZIO doesn't have a dependency on `sun.misc.SignalHandler`.

I have a vague memory / feeling that the issue is due to the `lazy val`s used in the `zio.VersionSpecific` trait. I might be wrong, but I remember reading somewhere that `lazy val`s for some Scala versions couldn't be used when compiling code using GraalVM's Native Image either. In Scala 3 specifically, I believe this issue was fixed in versions v3.2.0+ when lazy val's were re-implemented.

One thing you could potentially try is writing the plugin using sbt 2.x (which is still in Alpha stage) and see if that resolves it (since SBT 2.x uses Scala 3 instead of 2.12). I know this doesn't resolve your issue per-se but will at least help identify if that's indeed the cause of the issue.

**Comment by monktastic** [comment] 2024-10-11 15:07
@kyri-petrou Thanks. I may be misunderstanding your comment about ZIO not having a dependency on `sun.misc.SignalHandler`. You saw the code I linked where ZIO explicitly uses it in [PlatformSpecific](https://github.com/zio/zio/blob/6362961efb3fe0af160b6b5e76b2a3014531825d/core/jvm/src/main/scala/zio/internal/PlatformSpecific.scala#L43)?

```
  /**
   * Adds a signal handler for the specified signal (e.g. "INFO"). This method
   * never fails even if adding the handler fails.
   */
  final def addSignalHandler(signal: String, action: () => Unit)(implicit unsafe: zio.Unsafe): Unit = {
    import sun.misc.Signal
    import sun.misc.SignalHandler

    final case class ZIOSignalHandler(action: () => Unit) extends SignalHandler {
      private[zio] var signalHandler: SignalHandler = null
      override def handle(signal: Signal): Unit = {
        action()
        if (signalHandler != SignalHandler.SIG_DFL && signalHandler != SignalHandler.SIG_IGN) {
          signalHandler.handle(signal)
        }
      }
    }
```

**Comment by kyri-petrou** [comment] 2024-10-13 03:15
@monktastic apologies, I didn't see the linked code and for some reason when I searched for `SignalHandler` in the IDE it didn't come up 😕.

Let me reopen this issue and I'll try to add a fix for it. I don't think we can remove it altogether (I'll look into whether alternatives exist though) since we do need to be able to respond to signals, but I think we might be able to determine during runtime whether the platform supports `sun.misc.Signal` and only add the signal handlers if it does

**Closed as completed** 2024-10-22 02:31 UTC

**Comment by monktastic** [comment] 2024-10-22 14:05
Thanks @kyri-petrou! Any guesses when we'll get a release with this change?
