### ISSUE TITLE
Test with TestClock hangs sometimes

### ISSUE THREAD

**Issue by darl** [zio/zio#7493] opened 2022-11-02 09:53 UTC
ZIO Version: 2.0.3
```scala
object TestClockSpec extends ZIOSpecDefault {

  def spec = suite("TestClock")(
    test("sleep") {
      for {
        promise <- Promise.make[Nothing, Any]
        daemon =
          promise.succeed(()) *>
            ZIO.dieMessage("").catchAllCause(_ => ZIO.unit).repeat(Schedule.forever)

        _ <- daemon.forkDaemon
        _ <- promise.await
      } yield assertCompletes
    } @@ nonFlaky(5000)
  )
}
```

Sometimes hang with message:
```
+ TestClock
timestamp=2022-11-02T09:51:50.135977Z level=WARN thread=#zio-fiber-119 message="Warning: A test is using time, but is not advancing the test clock, which may result in the test hanging. Use TestClock.adjust to manually advance the time." location=dev.zio.quickstart.TestClockSpec.spec.daemon file=TestClockSpec.scala line=15
```

I think runtime cannot interrupt forked fiber.
In cases when test succeed something continues to consume CPU until sbt console got killed

**Comment by adamgfraser** [comment] 2022-11-02 10:24
@darl I have run this a couple dozen times and have never observed the test not terminate.

However, you are right that the fiber continues running in the background. This is expected behavior since you fork the fiber as a daemon fiber and never interrupt it and the fiber essentially does a busy loop.

The `TestClock` warning is a bit of a red herring here but is triggered because the implementation of `Schedule` does use time in its implementation and the test can occasionally take a long time to complete due to the busy loop and the fiber never being interrupted.

**Comment by darl** [comment] 2022-11-02 13:14
>  This is expected behavior since you fork the fiber as a daemon fiber and never interrupt it and the fiber essentially does a busy loop.

afaik all fibers interrupted by zio-test runtime after test completes.
Checked that with `2.0.2` - all daemon fibers got interrupted.
On `2.0.3` none of them interrupted

**Comment by darl** [comment] 2022-11-02 13:19
> I have run this a couple dozen times and have never observed the test not terminate.

Are you running them in same sbt session?

Replaced `.forkDaemon` with simple `.fork` and test hangs after 8 repetitions with stack trace:
```
"ZScheduler-Worker-7" #160 daemon prio=5 os_prio=31 cpu=41188,17ms elapsed=42,29s tid=0x000000013cdf1000 nid=0xed03 runnable  [0x0000000297960000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Throwable.fillInStackTrace(java.base@11.0.16.1/Native Method)
        at java.lang.Throwable.fillInStackTrace(java.base@11.0.16.1/Throwable.java:787)
        - locked <0x00000007bdccfbc8> (a java.lang.RuntimeException)
        at java.lang.Throwable.<init>(java.base@11.0.16.1/Throwable.java:270)
        at java.lang.Exception.<init>(java.base@11.0.16.1/Exception.java:66)
        at java.lang.RuntimeException.<init>(java.base@11.0.16.1/RuntimeException.java:62)
        at zio.ZIO$.$anonfun$dieMessage$1(ZIO.scala:3025)
        at zio.ZIO$$$Lambda$5415/0x00000008016c8840.apply(Unknown Source)
        at zio.ZIO$.$anonfun$failCause$1(ZIO.scala:3088)
        at zio.ZIO$$$Lambda$5420/0x00000008016cb840.apply(Unknown Source)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1115)
        at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:384)
        at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:496)
        at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:224)
        at zio.internal.FiberRuntime.run(FiberRuntime.scala:140)
        at zio.internal.ZScheduler.stealWork(ZScheduler.scala:123)
        at zio.internal.FiberRuntime.stealWork(FiberRuntime.scala:1415)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1022)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1052)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:995)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1052)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:918)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:995)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1052)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:995)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:918)
        at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1052)
        at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:384)
        at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:496)
        at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:224)
        at zio.internal.FiberRuntime.run(FiberRuntime.scala:137)
        at zio.internal.ZScheduler$$anon$3.run(ZScheduler.scala:457)
```

**Comment by adamgfraser** [comment] 2022-11-02 14:23
Interrupting them if they are forked with `forkDaemon` is not expected behavior. They are forked as daemon fibers so it is not correct to interrupt them.

**Comment by adamgfraser** [comment] 2022-11-02 19:46
Going to close this as not interrupting daemon fibers is expected behavior and the issue with interrupting a fiber that repeatedly captures a stack trace has now been fixed. Neither of these issues appear to relate to the `TestClock`.

**Closed as completed by adamgfraser** 2022-11-02 19:46 UTC
