### ISSUE TITLE
Unexpected behavior of `mapMParUnordered` with failures

### ISSUE THREAD

**Issue by gchudnov** [zio/zio#2547] opened 2019-12-31 11:20 UTC
I have the [following code](https://gist.github.com/gchudnov/638a7d49ee5161f9054fff2183a1c37c) (please note `mapMParUnordered`):

```scala
    Stream("a", "b", "c")
      .map(it => Either.cond(it == "a", it, new RuntimeException("invalid key")))
      .mapMParUnordered(4)(it => ZIO.fromEither(it))
      .run(Sink.drain)
      .foldM(
        e => {
          ZIO.effectTotal(logger.error("Application failed", e)) *> ZIO.succeed(1)
        },
        _ => {
          ZIO.succeed(0)
        }
      )
```

when runned, sometimes it completes normally and sometimes with an error.

My expectation was to complete it *always* with an error.
Is this the expected behavior?

With `mapMPar` it completes *always* with an error.

tried with RC-17 and current master.

**Comment by vasilmkd** [comment] 2020-01-01 10:52
I'm unable to reproduce the issue with this code snippet. Both `mapMParUnordered` and `mapMPar` always compete with the error code 1, and the error is logged.

**Comment by gchudnov** [comment] 2020-01-01 11:27
got it..
for me it is definitely not the case.. the result is quite stable and I get code 0 quite frequently..
on both my home and work machines.

**Comment by vasilmkd** [comment] 2020-01-01 11:39
Can you check out the ZIO codebase and try this in a console on master?

**Comment by gchudnov** [comment] 2020-01-01 14:19
yes, sure, will do it soon.

**Comment by reibitto** [comment] 2020-01-01 20:36
I'm also seeing what @gchudnov is seeing (or at least something similar to it).

With `mapMPar` I'm always getting the failure, which is what I would expect.

With `mapMParUnordered` I'm getting 3 different results:
- Succeeds
- Fails with "Application failed" alongside a "A checked error was not handled." warning.
- Fails with "Application failed" without a fiber warning.

Try changing the stream's size. With 2-4 elements, the stream seems to always complete successfully for me for the `mapMParUnordered` case (which is unexpected). With 5+ elements in the stream I always seem to get "Application failed".

However, if I run the Stream multiple times consecutively in one run, I can see "Application failed" even when I have less than 5 elements. This is when the fiber warnings being printed out are inconsistent for me.

Also, I think it might be possible that we're seeing different results due to different core counts and the zio.Runtime we're using? Not sure, but something to think about.

By the way, I tried this with RC17.

**Comment by iravid** [comment] 2020-01-01 21:20
I’m very interested in fixing this, so if you could submit a PR with a reproducing test that’d be a great start.

**Comment by gchudnov** [comment] 2020-01-02 09:45
yes, the behavior exactly as reibitto mentioned.
just reproduced on the latest master (hash: ca386ba8).

I'm using scala 2.13.1, machine with 8 cores, on the `DefaultRuntime` from zio.

Will try to get more details

**Comment by gchudnov** [comment] 2020-01-02 14:47
@iravid 
it looks it is a bit difficult to get the complete trace of the calls, since it affects the execution, but I noticed the following thing:

it looks there might be a race between `out.offer(Pull.end)` and `out.offer(Pull.halt(cause))` in [flatMapPar](https://github.com/zio/zio/blob/a64daa6406ec7cde1e32b1ed934cc44ec0d4f0ba/streams/shared/src/main/scala/zio/stream/ZStream.scala#L1311)

When the app completes without an error,
```
Breakpoint reached at zio.ZQueue$$anon$8.$anonfun$take$10(ZQueue.scala:601)
None <-- value returned from `ZQueue.take`, corresponds to `Pull.end`
```

and where there is an error:
```
reakpoint reached at zio.ZQueue$$anon$8.$anonfun$take$10(ZQueue.scala:601)
Traced(Fail(Some(java.lang.RuntimeException: invalid key)),ZTrace(I....
```

**Comment by vasilmkd** [comment] 2020-01-02 14:57
What is the timeline for this fix? Is it urgent? Because we're slowly moving towards errors are just normal events in the lifecycle of the stream, so a stream is not going to be torn down after it signals an error, and these combinators will require a rewrite either way.

I am going to work on that, I could maybe prioritize it higher. :)

**Comment by gchudnov** [comment] 2020-01-02 17:56
IMHO problems like these might delay the adoption of zio streams in production code.
as for me it is not urgent, but it would be great if it were fixed before the release of 1.0.

**Comment by jbenoit2011** [comment] 2021-07-26 18:42
Don't know if that's related but I also noticed a weird behavior of `mapMParUnordered`, during test writing I noticed that the output of stream using `mapMParUnordered` is different according to its position in test suite.

For example, in [this suite](https://scastie.scala-lang.org/Mz55E2v6QpC8jgByzKy7QQ) the 2nd test will fail (only on initial build in Scastie but on my computer it fails every time).

But in [that one](https://scastie.scala-lang.org/FYA79l7KTWKk1Dq74PvuRQ), the order of the tests have been reverted and it works.

I also noticed that replacing it with `mapMPar` does not produce that issue: https://scastie.scala-lang.org/BQcnPZm4QBqZeCeOJfhmeQ

**Comment by adamgfraser** [comment] 2021-07-26 21:45
I see the problem. Working on a fix.

**Comment by adamgfraser** [comment] 2021-07-27 06:18
Submitted #5325 to resolve this.

**Closed** 2021-07-27 13:39 UTC
Labels: bug, stream

**Comment by jbenoit2011** [comment] 2021-07-28 11:43
Thanks @adamgfraser, it solved the issue on my side.

**Comment by adamgfraser** [comment] 2021-07-28 11:43
@jbenoit2011 Awesome!
