### ISSUE TITLE
zio rc19 - Defect in zio.Has: Set(Any) 

### ISSUE THREAD

**Issue by regis-leray** [zio/zio#3629] opened 2020-05-18 14:12 UTC
The current code is compiling but cannot be executed im getting an error at runtime 

```scala
def putObject[R <: zio.Has[_]: Tag](content: ZStream[R, Throwable, Byte]): ZIO[R, IOException, Unit] = {
        val blocking: Has[Blocking.Service] = ???
        val z: ZIO[Blocking with R, IOException, Unit] = ???
            
        // java.lang.Error: Defect in zio.Has: Set(Any) statically known to be contained within the environment are missing
        z.provideSome[R](blocking.union[R])
}

val data: ZStream[Any, Nothing, Byte]  = ZStream.fromChunks(c)
putObject(data)
```

```
Fiber failed.
[info]     An unchecked error was produced.
[info]     java.lang.Error: Defect in zio.Has: Set(Any) statically known to be contained within the environment are missing
[info]         at zio.Has$HasSyntax$.prune$extension(Has.scala:136)
[info]         at zio.Has$HasSyntax$.union$extension(Has.scala:148)
[info]         at zio.s3.Test$$anon$1.$anonfun$putObject$3(Test.scala:108)
[info]         at zio.ZIO.$anonfun$provideSome$1(ZIO.scala:1139)
[info]         at zio.internal.FiberContext.evaluateNow(FiberContext.scala:538)
[info]         at zio.internal.FiberContext.$anonfun$fork$3(FiberContext.scala:706)
[info]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]         at java.base/java.lang.Thread.run(Thread.java:834)
[info]
```

**Comment by neko-kai** [comment] 2020-05-18 18:52
@regis-leray Hmm, the code you posted does not compile as-is. I've ran it modified like this:
```scala
```

**Comment by neko-kai** [comment] 2020-05-18 18:53
@regis-leray 
Could you please check if adding the following dependency to your project:
```scala
libraryDependencies += "dev.zio" %% "izumi-reflect" % "1.0.0-M2"
```
Fixes the issue?

**Comment by regis-leray** [comment] 2020-05-19 14:39
Here some code using zio-rc19, compile and im still getting the error 
im able to reproduce on scatie
https://scastie.scala-lang.org/typhsG0iRpKTPwo0C4QwXg

**Comment by neko-kai** [comment] 2020-05-19 17:37
@regis-leray Thanks for the reproduction! Looking into it

**Comment by neko-kai** [comment] 2020-05-19 17:48
This happens because `putObject(data)` ends up parameterized as ` putObject[Has[_]](data)` with the environment it runs again being `zio.ZEnv`

@adamgfraser This is frankly both correct and incorrect, `ZEnv` conforms to `Has[_]` AND there's no single service that is exactly equal to `_`, pruning assumes invariant parameters are unique, but that's not the case for wildcards. Not sure what should be done here.

**Comment by pshirshov** [comment] 2021-12-17 00:24
This may be somehow relevant: https://github.com/zio/izumi-reflect/issues/31

**Comment by guizmaii** [comment] 2024-12-17 06:47
Closing as it's a ZIO1 issue, which isn't maintained anymore

**Closed by guizmaii** 2024-12-17 06:47 UTC
Labels: bug
