### ISSUE TITLE
ZPipeline JVM timeout

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#6163] opened 2021-12-14 09:55 UTC
```
[info] - ZPipeline JVM
[info]   - Constructors
[info]     - Deflate
[info]       - JDK inflates what was deflated
[info] Timeout of 5 m exceeded.
[info]     - Inflate
[info]       - inflate what JDK deflated
[info] Timeout of 5 m exceeded.
[info]     - Gunzip
[info]       - gunzip what JDK gzipped, nowrap
[info] Timeout of 5 m exceeded.
[info]     - Gzip
[info]       - JDK gunzips what was gzipped
```

**Comment by adamgfraser** [comment] 2021-12-14 13:02
Yes I saw this as well.

**Comment by vigoo** [comment] 2021-12-15 08:18
Me too, could not reproduce locally yet

**Comment by eyalfa** [comment] 2023-02-22 20:54
is there any printouts/logs of the generated test case(s)?

**Comment by adamgfraser** [comment] 2023-02-22 22:17
You can add a debug statement to the test to see the generated test data but this issue is more than a year old, from before the release of ZIO 2.0, and I have not observed since then so going to close this.

**Closed by adamgfraser** 2023-02-22 22:17 UTC
Labels: bug, tests, flaky tests, zio2
