### ISSUE TITLE
Chunk crashes on pattern matching

### ISSUE THREAD

**Issue by tampler** [zio/zio#1176] opened 2019-07-13 14:59 UTC
I have a simple polymorphic producer and wanna do pattern matching on Chunk[A]. Here's how:
```scala
type BArr = Array[Byte]

private def produceOne[A](cfg: NetConfig, t: String, data: Chunk[A]): UIO[Unit] = ZIO.effectTotal {
    ....
    data match {
      case din: Chunk[String] => ....
      case din: Chunk[BArr]   => ....
      case _                  => ZIO.fail("Unknown input type")

    }
  }
```
When I call `produceOne[BArr]`, all works fine. When I call `produceOne[String]`, I get the following crash:
```bash
[error] zio.FiberFailure: Fiber failed.
[error] An unchecked error was produced.
[error] java.lang.ClassCastException: [B cannot be cast to java.lang.String
[error]         at zio.Chunk.map(Chunk.scala:249)
[error]         at zio.Chunk.map$(Chunk.scala:243)
[error]         at zio.Chunk$Singleton.map(Chunk.scala:806)
[error]         at zio.kafka.client.KafkaTestUtils$.$anonfun$produceOne$1(KafkaTestUtils.scala:24)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at zio.internal.FiberContext.evaluateNow(FiberContext.scala:339)
[error]         at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:599)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

The full code is [here](https://github.com/Clover-Group/zio-kafka/blob/be3cdbacfe434e641a0d8a30b503b9b63e75ce79/src/test/scala/zio/kafka/client/KafkaTestUtils.scala#L32)

Using Oracle JVM 8

**Comment by tampler** [comment] 2019-07-13 15:07
Crashes both on Oracle 8 and Oracle 11

**Comment by iravid** [comment] 2019-07-13 15:09
That's not a bug - `T` is erased at runtime, so you cannot distinguish between element types of chunk. See here: http://squidarth.com/scala/types/2019/01/11/type-erasure-scala.html. Same thing would happen with `List[T]`.

If you'd like to do this sort of type-casing, you can use a (lawless) typeclass; e.g.:
```scala
trait HowToProduce[A] {
  def apply(cfg: NetConfig, t: String, data: Chunk[A]): UIO[Unit]
}

private def produceOne[A](cfg: NetConfig, t: String, data: Chunk[A])(implicit htp: HowToProduce[A]): UIO[Unit] = htp(cfg, t, data)
```

**Comment by tampler** [comment] 2019-07-13 15:29
@iravid  thanks for your advice. I tried your implementation, but getting the same error. Pls check [here](https://github.com/Clover-Group/zio-kafka/blob/d1faca699024d0d39fac5bbd9aca8d1634bbff54/src/test/scala/zio/kafka/client/KafkaTestUtils.scala#L17)

Am I missing something? How do I improve my code ?

**Comment by iravid** [comment] 2019-07-13 15:56
Well you just moved the problem to `HowToProduce.apply`. You need a different instance of `HowToProduce` for every `A` you want to handle.

Closing this issue since this is not a bug.

**Closed by iravid** 2019-07-13 15:56 UTC

**Comment by kaishh** [comment] 2019-07-13 18:27
@tampler 
In the future you may avoid this type of errors by turning on all scalac warnings:
https://tpolecat.github.io/2017/04/25/scalac-flags.html
https://github.com/DavidGregory084/sbt-tpolecat

e.g. for me this fragment results in warning, clearly showing me that this kind of match won't work as i expect it to:

```scala
List[Any](1, 2, 3) match {
  case l: List[String] => l.map(_.length)
}
```

```
Warning:(53, 13) non-variable type argument String in type pattern List[String] (the underlying of List[String]) is unchecked since it is eliminated by erasure
    case l: List[String] => l.map(_.length)
```

**Comment by tampler** [comment] 2019-07-15 14:42
@iravid @kaishh Thanks guys for directions and advice. 
I was able to implement a polymorphic produce method, which works fine for me. Check [here](https://github.com/Clover-Group/zio-kafka/blob/f2e743bd1509809f767221ad8f29004af1f8b535/src/test/scala/zio/kafka/client/KafkaTestUtils.scala#L50)
