### ISSUE TITLE
Completely overhaul supervision

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1081] opened 2019-06-24 20:11 UTC
The drawbacks to the current supervision model are many:

 - It can consume lots of memory, potentially unlimited on Javascript
 - There are differences between JVM and Scala.js, because Scala.js does not support weak structures
 - Deterministic tests are difficult to write because of the non-determinism of garbage collection
 - It has to be explicitly turned on, and tracking child fibers has non-trivial costs

The main function of supervision is to interrupt child fibers when the parent has been interrupted.

This can be accomplished in a different way:

 - By allowing child fibers to share the same interruption variable as their parent

Because this behavior is not always desired, we can introduce a new `daemon` operator to severe the connection between parent and child.

### Benefits

 - No memory consumed for the feature
 - The model is the same across JVM and Scala.js
 - No reliance on non-deterministic garbage collection
 - Interruption-safe by default

As an example of the "safety by default", here is the simplest possible implementation of `zipPar`:

```scala
def zipPar[A, B](left: UIO[A], right: UIO[B]): UIO[(A, B)] = 
  for {
    fiberA <- left.fork
    fiberB <- right.fork
    a <- fiberA.join
    b <- fiberB.join
  } yield (a, b)
```

Notice how this implementation is "just correct" under the new model.

The new model makes it much safe to write resource-safe code using raw fibers.

### Drawbacks

We lose the ability to perform a "join" of the children fibers on exit of the parent. 

However, if this capability is desired, it can be implemented manually via explicit tracking of all child fibers.

### The Daemon Operator 

```scala
trait ZIO[R, E, A] { self =>
  def daemon: ZIO[R, E, A] = ZIO.daemon(self)
}
object ZIO {
   def daemon[R, E, A](zio: ZIO[R, E, A]): ZIO[R, E, A] = ???
}
```

### Forking All as Daemons 

```scala
ZIO.forkAll(list.map(_.daemon))
```

### Summary of Tasks

 - [ ] Introduce interruption variable inheritance
 - [ ] Introduce `daemon`
 - [ ] Delete `supervised`
 - [ ] Delete `unsupervised`
 - [ ] Delete `interruptChildren`
 - [ ] Delete `checkSupervised`
 - [ ] Delete `superviseStatus`
 - [ ] Delete `handleChildrenWith`

**Comment by NeQuissimus** [comment] 2019-06-24 20:14
![Yeah Baby Yeah](https://user-images.githubusercontent.com/628342/60048891-1fda2c80-969b-11e9-8f79-202b0419f589.png)

**Comment by iravid** [comment] 2019-06-24 20:16
Yes, this makes sense. I think I often wanted the ability to kill an entire subtree of fibers and it always seemed too difficult when it should be the default.

This is my intuition after some initial thoughts, will sleep on it :-)

**Comment by jdegoes** [comment] 2019-06-24 20:17
You will be able to kill the whole app, all the way down, assuming you're not using daemon anywhere.

**Comment by jdegoes** [comment] 2019-06-30 16:38
With this approach, we cannot easily support fork in recursive position:

```scala
def infiniteParents(doWork: UIO[Unit]): UIO[Unit] = 
  (doWork *> infiniteParents(doWork)).fork
```

I think it's possible, though, assuming the ancestors don't live forever.

/cc @iravid @kaishh

**Comment by iravid** [comment] 2019-06-30 17:25
I don't think I've implemented that sort of pattern before (but I can see where it could be useful).

**Comment by jdegoes** [comment] 2019-07-01 11:52
@iravid Seems fixable, but there's another issue.

Making, `fiber.interrupt` wait for the _descendants_ to finish is brittle. Any lost or garbage collected fiber along the way makes the interrupt non-terminating (of course, it can be forked).

I wonder how terrible it would be if `interrupt` only wait for the fiber, and not its descendants?

**Comment by iravid** [comment] 2019-07-01 12:09
Ouch. That's unfortunate. Making `interrupt` not wait for the descendants also sounds problematic, as we can't guarantee finalization ordering that way (e.g. if descendant fibers are using resources from parent fibers).

Of course if that's not solvable in a scalable way in the runtime we'll just need to implement it in userland when required.

**Comment by jdegoes** [comment] 2019-07-01 13:47
I think I can make `interrupt` wait for all descendants; I also think in the general case, this means that `interrupt` won't terminate.

The odds of a garbage collected fiber or `never` that's not interrruptible or promise that's never completed, etc., in the entire application hierarchy approach 1.0 quickly as you move up; so `interrupt` will terminate in the low levels, generally, and not terminate in the higher-levels.

What we're really missing to make this "rock solid" is the ability to auto-terminate fibers that are garbage collected. Then you only need to worry about uninterruptible `never` (and its equivalents), which of course is possible but avoidable with discipline.

**Comment by iravid** [comment] 2019-07-01 13:54
We can use a ReferenceQueue for that, right?

**Comment by jdegoes** [comment] 2019-07-01 14:01
@iravid 

Yes, in theory. Every time we suspend a fiber, we could add a weak reference to the fiber to a reference queue, storing the "cleanup action"; then a separate (blocking) thread could go through and cleanup stuff, ensuring all garbage collected fibers terminate life (ab)normally.

Then, in theory, the only reason an `interrrupt` could hang is if an async action has been made uninterruptible. Which is a design decision we could revisit...

**Comment by iravid** [comment] 2019-07-01 14:04
Yup! Sounds like what I had in mind. The blocking thread shouldn't be doing any heavy lifting, right? Just remove the garbage-collected fibers from the interruption variable they participated in.

**Comment by jdegoes** [comment] 2019-07-01 14:07
It's sole purpose would be cleanup of garbage collected fibers, e.g. running their "finalizers" if they are garbage collected. 

As part of the finalization process, the fiber can terminate normally (via `FiberContext#done()` inside RTS), which can then notify the parent fiber that the child has terminated, providing a hook to resume interruption in the parent.

**Comment by iravid** [comment] 2019-07-01 14:21
This sounds really exciting. And innovative - Akka, for example, keeps strong references for the actor hierarchy.

**Comment by kaishh** [comment] 2019-07-01 15:37
Note if you're trying to use JVM finalizers – JVM finalizers are not reliable! https://github.com/classgraph/classgraph/issues/257#issuecomment-428538903

**Comment by jdegoes** [comment] 2019-07-01 16:35
@kaishh Not necessary, can be done entirely through weak references +/- reference queues.

All right, so I think the following changes are necessary for maximum coherence:

 - **Async Interruption**. Async regions are _always interruptible_. This will likely break some Cats Effect laws but I'm not sure. We need a guarantee that any `never` or equivalent can always be terminated to completely avoid _hanging interrupt_.
 - **GC Interruption**. If a fiber is garbage collected, then it must be wound-down in a sane fashion, running all finalizers, and failing for reason of interruption. _Currently no library provides this guarantee, a garbage collected fiber will never run finalizers in all major libraries._

If the above have iron-clad guarantees, it means that an `interrupt` which awaits descendent fibers will have sane and well-defined behavior.

The semantics of this WRT `daemon` need to be formalized.

**Comment by iravid** [comment] 2019-07-01 16:47
Do we really want GC interruption to run finalizers? A fiber going out of scope isn't really the same as a fiber actually ending.

**Comment by jdegoes** [comment] 2019-07-01 16:50
@iravid A fiber has to have a well-defined lifecycle for `interrupt` to never hang.

Anway, there's a subtle leak right now:

```scala
openFile.bracket(closeFile)(useFile)
```

If `useFile` has some async action that never completes, then the file will never be closed.

As long as there is a reference to the fiber, in theory, it _could_ complete, but when there are no more references to the fiber, when it becomes garbage collected, then in it can _never_ complete, so it seems like the right thing to do is interrupt it and wind it down.

**Comment by kaishh** [comment] 2019-07-01 16:51
@jdegoes 
Hmm, on async interruption - yeah, this will break laws. It's also not compositional and might leak resources. I think CE Concurrent.start might probably have be `daemon` for the other laws too.

@iravid 
I think we don't, except for one case where it's non-daemon and the parent fiber is ending/interrupting. But then we have to accumulate fiber finalizers and/or hold strong references to children so that we can run finalizers "exactly" when the parent is dying.

**Comment by iravid** [comment] 2019-07-01 16:54
Sorry, I don't follow :-) In this snippet:
```
openFile.bracket(closeFile)(useFile)
```

If `useFile` never ends (by mistake or by design), then the finalizer should never run. Whether that is a leak or not is subjective

**Comment by kaishh** [comment] 2019-07-01 16:54
@jdegoes 
I think the intention here is to never close the resource though. e.g. we've used this pattern to create http4s server before we added cats Resource support to distage: `unsafeRun(server.resource.use(IO.never).fork)`

**Comment by jdegoes** [comment] 2019-07-01 17:00
> If useFile never ends (by mistake or by design), then the finalizer should never run. Whether that is a leak or not is subjective

I think there's a difference between _may_ never end, and _could_ never end, though. If the reference is live, it could end at some point; or if there is active work, it could end. But if it's GC'd, it cannot end.

> I think the intention here is to never close the resource though. e.g. we've used this pattern to create http4s server before we added cats Resource support to distage: unsafeRun(server.resource.use(IO.never).fork)

Hmmm, I wonder if the fiber is GC'd? Would be a good point for not winding down GC'd fibers.

On the flip-side, it would mean a need to introduce _yet another fiber failure state_, e.g. `Cause.Abandoned` or something, because the fiber would still need well-defined life-cycle.

**Comment by kaishh** [comment] 2019-07-01 17:06
I think it must be GC'd in this pattern because there's no reference to it outside and `never` moves it out of the queue forever too. Hell, if that fiber isn't GC'd, there must be no way to define an 'abandoned' fiber at all :P

You may or may not want to add another Cause branch... A GC'd fiber is always isomorphic to `never` - and this isn't interesting, even discovering one isn't interesting! But there is a difference with `Cause.Interrupted` because finalizers are never ran.

**Comment by iravid** [comment] 2019-07-01 17:06
Ok, I agree about "can never end", but I think the semantic of "has been garbage collected" is something you don't really want to think about, unless you're writing low-level code that uses weak references. I mean, we're now introducing another set of semantics into the fiber lifecycle that is usually not taken into account.

**Comment by jdegoes** [comment] 2019-07-01 17:32
> I think it must be GC'd in this pattern because there's no reference to it outside and never moves it out of the queue forever too. Hell, if that fiber isn't GC'd, there must be no way to define an 'abandoned' fiber at all :P

I think you are right, the fiber is essentially done (after creating the resource), except for `never`, which will never complete, so it must be GC'd.

Well, not quite: the fiber is returned from `unsafeRun()` so it cannot be garbage collected. But if you change the `.fork` to `.fork.unit`, then it would be GC'd.

The question is how important is it to support this pattern? Maybe it is important merely for predictability: maybe it's better to never run a finalizer than to run it during random GC.

>  I mean, we're now introducing another set of semantics into the fiber lifecycle that is usually not taken into account.

Although when teaching ZIO, I have had this question before: _If a fiber is garbage collected, will its acquired resources be safely released?_ I had to think about that for a second: the answer is no, because the fiber does not end life in the normal way. It's disconcerting that resources can be leaked in this way, although semantically it's the same as leaking through `acquire.bracket(release)(IO(while(true){ }))`. It's just the latter is very obvious and easy to detect, whereas a GC'd fiber is the worst thing that can happen from a debugging perspective.

**Comment by jdegoes** [comment] 2019-07-01 17:38
Another random idea here:

We could do a hard-ref from parent to child. That is, the parent always keeps track of _all_ children. When the children end life, the reference is removed; when `daemon` is used, the parent's reference to the child is removed.

**Comment by iravid** [comment] 2019-07-01 18:03
Heh, that question is kind of like asking, "does a tree falling in the forest make a sound?". It seems to me that fibers going out of scope and being garbage collected is something you shouldn't really care about. If you care about releasing the resources, release them explictly. However I'm going to let this go because I think I'm not going to run into this in practice.

With hard-refs and terminated children removed eagerly, that sounds like effectively the same guarantees on memory usage as weak refs.

**Comment by jdegoes** [comment] 2019-07-01 18:35
> With hard-refs and terminated children removed eagerly, that sounds like effectively the same guarantees on memory usage as weak refs.

The practical difference is that if you spin up an unending loop that forks off fibers forever, then a weak ref solution (like present) will allow you to bound the memory usage of that, assuming sufficient fibers are GC'd; whereas in a hard-ref scenario, you will consume unbounded memory.

**Comment by iravid** [comment] 2019-07-01 18:37
But if they're still running, they won't be GC'd anyway. And you're bounded by the amount of `FiberContext` instances you can hold.

If they terminate, they get removed in the hard ref impl and get GC'd in the weak ref impl. What am I missing?

**Comment by jdegoes** [comment] 2019-07-02 00:42
@iravid 

A code snippet is worth a thousand words:

```scala
IO.never.fork.forever
```

The parent fiber will exhaust all memory on the heap, because it tracks hard references to fibers that will never complete, and never be garbage collected.

Of course, if the parent were to be terminated, it would terminate the children, but in this hypothetical scenario, the parent runs forever... or at least until all the memory is gone.

Hard refs are highly subject to heap exhaustion in weird scenarios.

If you flip that, and make the child hold a hard ref to the parent, then the child can be GC'd which will block the parent forever.

I'd love a hard ref solution but if we go there, it will come with tradeoffs, albeit they will be the same across JVM and JS. 

For a soft ref solution the fundamental decision is:

 - Interrupt GC'd fibers
 - Do not interrupt GC'd fibers, make a new `Cause.Empty`

**Comment by iravid** [comment] 2019-07-02 04:00
Ah, thanks! That makes things clearer. 

My intuition is that GC'd fibers should not be interrupted, as they have not been explicitly ended / interrupted. That would be least surprising, in my view.

**Closed** 2019-11-12 03:16 UTC
