### ISSUE TITLE
Optimize parSequence

### ISSUE THREAD

**Issue by neko-kai** [zio/zio#2371] opened 2019-11-30 19:41 UTC
As per @Avasil's [benchmarks](https://gist.github.com/pk044/181b32f9af380c9230d8512d14233c2a) (https://github.com/zio/zio/pull/2290#event-2821787971) `ZIO.parSequence` has a long way to go to get good performance. Any contributions to optimize it or related methods are welcome!

**Comment by vasilmkd** [comment] 2019-12-02 15:12
Possibly a duplicate of #1182, but it needs more visibility. Either way, linking to the previous issue.

**Comment by horned-sphere** [comment] 2019-12-18 23:25
I've made attempt at this in [this PR](https://github.com/zio/zio/pull/2492). The implementation is fairly ugly but it does work and is faster (I've attached the benchmark comparison). Any feedback on it would be greatly appreciated. 

If you think it has any merit, the change in implementation has broken an assumption of a test case in the stack tracer which I'd like to get some advice on before trying to fix it.

**Comment by kitlangton** [comment] 2020-03-22 19:37
Should this issue be closed since #2492 got merged?

**Closed** 2021-01-22 22:01 UTC
Labels: good first issue, performance
