### ISSUE TITLE
Remove extraneous "ZIO" from home page and sub pages

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#961] opened 2019-06-04 13:14 UTC
On the home page, and on all subpages, ZIO appears both as logo and as text.

The text should be removed.

<img width="187" alt="Screen Shot 2019-06-04 at 7 14 13 AM" src="https://user-images.githubusercontent.com/156745/58881908-676f2900-8698-11e9-8ea1-dc20e0880240.png">
<img width="203" alt="Screen Shot 2019-06-04 at 7 14 04 AM" src="https://user-images.githubusercontent.com/156745/58881913-69d18300-8698-11e9-80f9-586b0321e89b.png">

/cc @Vilkina

**Comment by Vilkina** [comment] 2019-06-04 13:15
I'll take this.

**Comment by jdegoes** [comment] 2019-06-04 13:18
@Vilkina Thank you!

**Comment by Vilkina** [comment] 2019-06-04 13:38
@jdegoes where I can find documentation? I forgot the name of this plugin for web.

**Comment by jdegoes** [comment] 2019-06-04 13:45
It changed, it is now using Docusaurus. I have not build the website myself, I think we need a guide to building the website.

Perhaps @LGLO can put a small guide together about the website?

**Comment by Vilkina** [comment] 2019-06-04 13:47
> It changed, it is now using Docusaurus. I have not build the website myself, I think we need a guide to building the website.
> 
> Perhaps @LGLO can put a small guide together about the website?

I found documentation https://scalameta.org/mdoc/docs/docusaurus.html
https://docusaurus.io/docs/en/site-creation https://scalameta.org/mdoc/docs/installation.html#sbt

**Comment by Vilkina** [comment] 2019-06-04 13:49
<img width="1086" alt="Screen Shot 2019-06-04 at 4 48 02 PM" src="https://user-images.githubusercontent.com/3358827/58884211-9f05c180-86e8-11e9-89d9-7f75b9385954.png">
I found "problem". I just need to learn how to run zio.dev locally so that I can test the changes

**Comment by ghostdogpr** [comment] 2019-06-04 13:54
@Vilkina there are instructions about how to build it locally here: https://github.com/zio/zio/pull/784

The problem is that this title `h2` comes from the Docusaurus template, not directly from our code. I think it takes `title` defined in siteConfig.js. Maybe we can make it empty and add `ZIO` to the `tagline`?

**Comment by Vilkina** [comment] 2019-06-04 14:59
> #784

tnx, much easier now. I thought about display: none somewhere in css if it is possible.

**Comment by LGLO** [comment] 2019-06-04 15:14
Sometimes I feel I'm too slow for pace of this project, you are turbo people!

I think the main problem here is that our logo is redundant with library name.
We can take a look how to use this text in other way like https://hemerajs.github.io/hemera/ or https://react-leaflet.js.org/ - they also have textual logo.
Also +1 for not displaying any text, just the image.

**Comment by Vilkina** [comment] 2019-06-04 15:32
> We can take a look how to use this text in other way like https://hemerajs.github.io/hemera/ or https://react-leaflet.js.org/ - they also have textual logo.
> Also +1 for not displaying any text, just the image.
I like the https://react-leaflet.js.org/ . I need to go now. I'm planning to fix this issue tomorrow morning. But if you want to fix and merge it today - please do :)

**Comment by Vilkina** [comment] 2019-06-04 15:38
But the easiest way to fix this is override css (or we have already overwritten css file? ): 
fixedHeaderContainer header .headerTitleWithLogo {
    display: none;
    font-size: 1.25em;
    line-height: 18px;
    margin: 0;
    position: relative;
    z-index: 9999;
}

but only if we won't use this style  "header .headerTitleWithLogo" on other pages. 

<img width="1228" alt="Screen Shot 2019-06-04 at 6 33 39 PM" src="https://user-images.githubusercontent.com/3358827/58892916-cadc7380-86f7-11e9-9d59-e2af0b17e29f.png">

**Comment by ghostdogpr** [comment] 2019-06-04 21:02
Sounds good to me!

**Comment by Vilkina** [comment] 2019-06-05 09:52
<img width="767" alt="Screen Shot 2019-06-05 at 12 47 52 PM" src="https://user-images.githubusercontent.com/3358827/58947478-b00a0d80-8790-11e9-9512-d3c705dd974e.png">
I think I need to fix this before  build it locally :)

**Comment by iravid** [comment] 2019-06-05 09:55
try pulling master, I think that was fixed there

**Comment by Vilkina** [comment] 2019-06-05 11:56
> try pulling master, I think that was fixed there

not yet

**Comment by iravid** [comment] 2019-06-06 06:47
@Vilkina oh yeah, sorry, didn't notice that was in the docs. will push a fix now

**Comment by Vilkina** [comment] 2019-06-06 08:10
@iravid I've fixed this error yesterday locally but I have another error: 
<img width="1280" alt="Screen Shot 2019-06-06 at 11 06 10 AM" src="https://user-images.githubusercontent.com/3358827/59017170-9679cc00-884b-11e9-886c-d8b7a15367e9.png">

Error: You have 'doc' in your headerLinks, but no 'scalaz-zio-docs/target/mdoc' folder exists one level up from 'website' folder. Did you run `docusaurus-init` or `npm run examples`? If so, make sure you rename 'docs-examples-from-docusaurus' to 'docs'. I'll try to fix it :)

**Comment by ghostdogpr** [comment] 2019-06-08 18:12
@Vilkina hmm I didn’t get that one before but I’m on a trip without a laptop so I can’t check right now. Maybe it’s related with the renaming from scalaz-zio to zio? It’s weird that it looks for scalaz-, I thought we removed all of them. Do you have the latest master?

**Comment by Vilkina** [comment] 2019-06-10 07:08
@ghostdogpr, working now. Someone fixed those files. 
<img width="755" alt="Screen Shot 2019-06-10 at 10 06 43 AM" src="https://user-images.githubusercontent.com/3358827/59178375-8291db00-8b67-11e9-8698-32a0b14c1edc.png">
<img width="921" alt="Screen Shot 2019-06-10 at 10 05 44 AM" src="https://user-images.githubusercontent.com/3358827/59178456-b3721000-8b67-11e9-833b-a2af079164a9.png">

**Comment by ghostdogpr** [comment] 2019-07-07 22:30
Closed by #1143

**Closed by ghostdogpr** 2019-07-07 22:30 UTC
