### ISSUE TITLE
Possible scope issue after upgrading to RC21-2 (Performance)

### ISSUE THREAD

**Issue by sebver** [zio/zio#3926] opened 2020-07-01 12:36 UTC
I still have some issues after upgrading to RC21-2 with the same code sample as in #3910. After hitting the endpoint a few times the server doesn't respond, maybe because of issues wrt the scope fix of yesterday.

https://github.com/sebver/zio-http4s-scope-issue

The odd thing is that this becomes very noticeable as soon as you run it in a container. We didn't notice it yesterday because we weren't doing that, so I've updated the example/readme. You should notice it really quickly now.

I've tested it with RC21-1 and there it works (but with the defect being logged). On RC20 it behaves normally.

**Comment by fsvehla** [comment] 2020-07-01 13:56
I can also confirm that I still see it.

**Comment by adamgfraser** [comment] 2020-07-01 14:02
Okay, on it. Thanks for reporting and for the reproducer!

**Comment by adamgfraser** [comment] 2020-07-01 18:47
Is everyone who is seeing this issue using `interop-cats`? My current hypothesis is that the issue is related to the interaction between that and the fiber supervision changes.

In particular, my understanding is that in `cats-interop` we want to fork everything on the global scope (because applications that are built using Cats Effect don't know anything about ZIO's fiber supervision model and can't be relied on to properly handle fibers per the supervision model / don't have the combinators to do so). If this is correct then the parent scope should never be closed in `FiberContext#fork` for a Cats Effect application (because the global scope is always open). But adding debug statements it appears that fibers are being forked on scopes other than the global scope, which then leads to them immediately being interrupted when the scope they are forked on is already closed.

Copying @ghostdogpr and @neko-kai.

**Comment by ghostdogpr** [comment] 2020-07-02 00:05
Hmm in interop-cats we always use `forkDaemon` and never `fork`. But maybe this could come from inside another operator. Do you have any idea where that fork operation come from?

**Comment by ghostdogpr** [comment] 2020-07-02 00:20
The only non-global fork done in this example comes from a call to `raceTimeout` in http4s. Our implementation for `race` is here https://github.com/zio/interop-cats/blob/332c7ea4debeeb70caae66850e785af86f655dad/interop-cats/shared/src/main/scala/zio/interop/cats.scala#L231 
See anything wrong with it?

**Comment by adamgfraser** [comment] 2020-07-02 00:57
Yes I think the issue is that we are doing internal forks in those combinators that are on local scopes. For example in the snippet below both raced fibers are forked on the scope of the parent fiber instead of the global scope:

```scala
package zio

object Example extends App {

  def run(args: List[String]): URIO[ZEnv,ExitCode] =
    race(showScope, showScope).exitCode

  val showScope: UIO[Unit] =
    ZIO.descriptorWith(descriptor => UIO(println(descriptor.scope)))

  def race[R, A, B](fa: RIO[R, A], fb: RIO[R, B]): RIO[R, Either[A, B]] =
    (fa.map(Left(_)).interruptible raceFirst fb.map(Right(_)).interruptible)
}
```

**Comment by Fristi** [comment] 2020-07-13 11:26
Would this fix it ?

```scala
def forkGlobal[R, E, A](zio: ZIO[R, E, A]) =
    zio.interruptible.forkDaemon.flatMap(_.join)

  def race[R, A, B](fa: RIO[R, A], fb: RIO[R, B]): RIO[R, Either[A, B]] =
    forkGlobal(fa.map(Left(_))) raceFirst forkGlobal(fb.map(Right(_)))
```

**Comment by adamgfraser** [comment] 2020-07-14 15:31
@sebver @fsvehla Can you try using this snapshot of `cats-interop` and see if that resolves the issue `2.1.3.0-RC16+8-8ebd453e-SNAPSHOT`?

**Comment by YuvalItzchakov** [comment] 2020-07-15 05:59
@adamgfraser Can confirm this fixes the issue 🎊 

```shell
Server Software:
Server Hostname:        localhost
Server Port:            8080

Document Path:          /v1/api/health
Document Length:        0 bytes

Concurrency Level:      25
Time taken for tests:   2.501 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      75000 bytes
HTML transferred:       0 bytes
Requests per second:    399.86 [#/sec] (mean)
Time per request:       62.521 [ms] (mean)
Time per request:       2.501 [ms] (mean, across all concurrent requests)
Transfer rate:          29.29 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2   2.3      0      22
Processing:     5   37  38.5     28     996
Waiting:        4   31  37.2     24     984
Total:         10   38  38.2     29     996

Percentage of the requests served within a certain time (ms)
  50%     29
  66%     36
  75%     43
  80%     48
  90%     71
  95%     90
  98%    115
  99%    127
 100%    996 (longest request)
```

**Comment by ghostdogpr** [comment] 2020-07-15 07:07
Great news! I will release cats-interop.

**Comment by ghostdogpr** [comment] 2020-07-15 07:28
cats-interop is released: https://github.com/zio/interop-cats/releases/tag/v2.1.4.0-RC17

Closing this issue, thanks to everyone who helped!

**Comment by sebver** [comment] 2020-07-15 14:50
@Fristi @ghostdogpr @adamgfraser I can also confirm it's fixed, thanks everyone!

I did notice a performance degradation. With the example I'm getting the following numbers after some runs:
RC21-2:
Requests per second:    837.22 [#/sec] (mean)
RC20:
Requests per second:    1426.12 [#/sec] (mean)

**Comment by Fristi** [comment] 2020-07-20 06:04
On a local branch I added a benchmark to zio for race:

```
Benchmark                  (depth)   Mode  Cnt      Score      Error  Units
IORaceBenchmark.cats            20  thrpt   15  77022,445 ± 2313,434  ops/s
IORaceBenchmark.monix           20  thrpt   15  77060,933 ±  896,285  ops/s
IORaceBenchmark.zio             20  thrpt   15  44046,091 ±  559,027  ops/s
IORaceBenchmark.zioTraced       20  thrpt   15  38394,292 ±  508,840  ops/s
```

I think there is the underlying problem for http4s being slower.

**Comment by adamgfraser** [comment] 2020-07-20 17:48
@sebver Is that on your production code or the reproducer? Could you add something to the reproducer that makes it easy to see the different in throughput? That could really help us as we explore different changes to see if they actually move the needle on this.

**Comment by sebver** [comment] 2020-07-20 19:08
This was on the reproducer. I'll try to make a more minimal example tomorrow, with easy ways of testing.

**Comment by sebver** [comment] 2020-07-27 08:16
So I mentioned this to Adam earlier, but seems good to mention it here as well.

After some more performance testing on the reproduction I felt like the difference wasn't as big and consistent as I originally thought it was. Meanwhile I've put the latest version in production in our real world application, and I'm not seeing any performance issues whatsoever. So, although there _may_ be somewhat of a regression on this specific reproduction (which is not a very realistic scenario), I don't think it has much of an impact.

I've understood more performance work will happen post 1.0, so I'm wondering if we should close this issue for now?

**Comment by ghostdogpr** [comment] 2020-07-27 08:42
It is just circumstantial evidence but I am also working on load testing at work and I haven't seen any degradation either.

**Closed** 2020-10-08 00:25 UTC
Labels: bug
