### ISSUE TITLE
Compilation Issue with Latest Nightly Version of Dotty

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#2412] opened 2019-12-04 02:09 UTC
Was reported this morning on Discord and I was able to replicate locally tonight. Compilation fails for `stacktracer` with the below error message. I'm not sure if this is directly related to `stacktracer` or just because it is at the base of our dependency graph. Would be good to get this resolved before the next Dotty release candidate if possible so we can can support it when it becomes available.

Copying @neko-kai and @smarter.

```
[error] not found: /drone/src/library/src/scala/internal/Quoted.scala
[error] not found: /drone/src/library/src/scala/internal/Quoted.scala
[error] not found: /drone/src/library/src/scala/internal/Quoted.scala
[error] not found: /drone/src/library/src/scala/quoted/QuoteContext.scala
[error] not found: /drone/src/library/src/scala/quoted/QuoteContext.scala
[error] not found: /drone/src/library/src/scala/quoted/QuoteContext.scala
```

**Comment by neko-kai** [comment] 2019-12-04 04:44
We don't use any dotty apis, including Quote/QuoteContext. Looks like a dotty breakage unrelated to zio based on that trace...

**Comment by smarter** [comment] 2019-12-04 11:58
Even if you can't easily minimize it, could you open an issue in the dotty repo with reproduction steps?

**Comment by adamgfraser** [comment] 2019-12-04 11:58
Sure. Will do!

**Comment by smarter** [comment] 2019-12-13 10:03
This should be fixed as of the latest dotty nightly.

**Comment by adamgfraser** [comment] 2019-12-14 05:41
I can confirm the issue has been resolved.

@smarter Thank you for your help with this!

**Closed** 2019-12-14 09:05 UTC
Labels: dotty
