### ISSUE TITLE
`zio-test` executed test count in summary is off

### ISSUE THREAD

**Issue by tjarvstrand** [zio/zio#8250] opened 2023-07-07 09:38 UTC
version: zio-2.0.15

When running tests using `sbtTest`, the summary stating how many tests have been run is off. It seems to be multiplied by some factor close to the number of suites executed.

Here's a simple reproduction: https://github.com/tjarvstrand/zio-test-repro

Running `sbt test` in that repo reports that 8 tests have been run, even though there are only 4.

**Comment by adamgfraser** [comment] 2023-07-07 11:27
Duplicate of #8214.

**Closed as completed by adamgfraser** 2023-07-07 11:27 UTC
