### ISSUE TITLE
Scala-js compile fails after moving from 2.0.2 to 2.0.3 or 2.0.4

### ISSUE THREAD

**Issue by KeithGrant** [zio/zio#7561] opened 2022-11-24 18:03 UTC
It appears the zio library versions 2.0.3/4 refer to a java class. Version 2.0.2 compiles successfully.

[error] Referring to non-existent method zio.VersionSpecific$$anon$1.apply(java.lang.Object)java.lang.Object
[error]   called from java.util.HashMap.computeIfAbsent(java.lang.Object,java.util.function.Function)java.lang.Object
[error]   called from zio.VersionSpecific.taggedIsSubtype(izumi.reflect.macrortti.LightTypeTag,izumi.reflect.macrortti.LightTypeTag)boolean
[error]   called from zio.package$.taggedIsSubtype(izumi.reflect.macrortti.LightTypeTag,izumi.reflect.macrortti.LightTypeTag)boolean
[error]   called from zio.ZEnvironment$$anon$1.get(izumi.reflect.macrortti.LightTypeTag,zio.Unsafe)java.lang.Object
[error]   called from zio.ZEnvironment.get(zio.package$Tag)java.lang.Object
[error]   called from private zio.ZIO$.consoleWith$$anonfun$1(scala.Function1,zio.ZEnvironment)zio.ZIO
[error]   called from zio.ZIO$.consoleWith(scala.Function1,java.lang.Object)zio.ZIO
[error]   called from zio.Console$.printError(scala.Function0,java.lang.Object)zio.ZIO
[error]   called from private zio.Fiber$.dumpAll$$anonfun$1$$anonfun$1(java.lang.Object,java.lang.String)zio.ZIO
[error]   called from private zio.Fiber$.dumpAll$$anonfun$1(java.lang.Object,zio.Fiber$Dump)zio.ZIO
[error]   called from zio.Fiber$.dumpAll(java.lang.Object)zio.ZIO
[error]   called from private static zio.ZIOApp.$anonfun$3(zio.Runtime,java.lang.Object)void
[error]   called from private static zio.ZIOApp.$anonfun$adapted$1(zio.Runtime,java.lang.Object)java.lang.Object
[error]   called from private static zio.ZIOApp.installSignalHandlers$$anonfun$1(zio.Runtime,java.lang.Object,zio.Unsafe)void
[error]   called from private static zio.ZIOApp.installSignalHandlers$$anonfun$adapted$1(zio.Runtime,java.lang.Object,zio.Unsafe)java.lang.Object
[error]   called from zio.ZIOApp.installSignalHandlers(zio.Runtime,java.lang.Object)zio.ZIO
[error]   called from com.grant.Main$.installSignalHandlers(zio.Runtime,java.lang.Object)zio.ZIO
[error]   called from private zio.ZIOAppPlatformSpecific.main$$anonfun$1(java.lang.Object,zio.Runtime)zio.ZIO
[error]   called from zio.ZIOAppPlatformSpecific.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   java.util.concurrent.ConcurrentHashMap$InnerHashMap
[error]   java.util.LinkedHashMap
[error]   java.util.HashMap
[error]   zio.package$
[error]   zio.ZEnvironment$$anon$1
[error]   zio.ZEnvironment
[error]   zio.ZIO$
[error]   zio.Console$
[error]   zio.Fiber$

**Comment by adamgfraser** [comment] 2022-11-24 18:55
Duplicate of #7496.

**Closed as completed by adamgfraser** 2022-11-24 18:55 UTC
Labels: javascript
