### ISSUE TITLE
ZIO Test: Develop example suites

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1284] opened 2019-07-30 00:04 UTC
Example test suites will show people how to use ZIO Test, and provide a "compile time test" ensuring that the syntax is supported.

We should have 3 short specs, and 3 medium specs, in varying complexity levels.

### Short Simple

10 line of code test, which only tests simple truths (no effects).

### Short Moderate

10 line of code test, which tests effectful operations.

### Short Complex

15 line of code test, which tests effectful operations with aspects and resource management.

### Medium Simple

50 line of code test, which only tests simple truths (no effects).

### Medium Moderate

50 line of code test, which tests effectful operations.

### Medium Complex

65 line of code test, which tests effectful operations with aspects and resource management.

**Comment by edvmorango** [comment] 2019-07-30 03:37
I would like to give it a shot.

**Comment by jdegoes** [comment] 2019-07-30 05:09
@edvmorango Thank you!

**Comment by jdegoes** [comment] 2019-07-30 15:59
ScalaTest has some very nice examples on their website. They're not quite realistic (most of them), but they give a feel for the library.

Specs2 has a number, front and center on the home page.

**Comment by edvmorango** [comment] 2019-07-30 16:30
Hey, @jdegoes I'll start work in it today, but I have some doubts:

1 - Where should I put these new specs (I'm thinking about core-tests/shared)? 

2 - By `aspect` did you mean PBT?

3 - Do you think to create two different specs, one with realistic tests and one more similar to ScalaTest/Specs2 a good idea?

**Comment by jdegoes** [comment] 2019-07-30 17:14
1. I'd do a new top-level project `examples` that we can put ZIO examples, ZIO test examples, etc.
2. By Aspect, I mean `TestAspect`.
3. Yes, that sounds like a good idea to me.

**Comment by edvmorango** [comment] 2019-08-02 02:49
Hey, @jdegoes  I'm working at this issue, after creating the first suit:

```
   suite("Operations")(
     test("(1 + 1) must be 2") {
       assert[Int](1 + 1, Predicate.equals(2))
     }
      ,
     test("(10 - 5) must be 5") {
       assert[Int](10 - 5, Predicate.equals(5))
     }
   )
```

I executed using the `DefaultRunnableSpec`. When I run the tests individually they work perfectly, but when I execute the suit none of them run. I modified the `run` function inside `TestRunner`  from parallel execution strategy to sequential:

```final def run(spec: Spec[L, T]): UIO[ExecutedSpec[L]] =
    executor.execute(spec, ExecutionStrategy.Sequential).flatMap { results =>
      reporter.report(results) *> ZIO.succeed(results)
 }
```

Now the suite execution is working as I expected. Is this the expected behavior, or I'm doing something wrong and don't have to change the `ExecutionStrategy`?

**Comment by ghostdogpr** [comment] 2019-08-02 14:44
@edvmorango I just gave it a try and it seems to run well even with Parallel? Can you post your whole code and how you run it?

@jdegoes @adamgfraser 
One thing I noticed was that because of `System.exit(0)` in `RunnableSpec`, the sbt session gets stopped when the test completes.

Another thing, if I change the test to fail, the reporting line is repeated, not sure why?
```
  - (1 + 1) must be 2
    2 did not satisfy equals(3) // in yellow
    2 did not satisfy equals(3) // in cyan
```

**Comment by adamgfraser** [comment] 2019-08-02 14:49
@ghostdogpr @jdegoes Regarding the error reporting, we generally print one line with the entire predicate and the failing subpredicate highlighted, and then a second line with just the failing subpredicate. We should probably add a check for whether the predicate is equal to the subpredicate (i.e. it is a simple predicate with no subpredicates) and in that case only print a single line. I can take that issue and submit a PR on it.

**Comment by jdegoes** [comment] 2019-08-02 15:05
@edvmorango It should work the same in parallel or sequentially. If you can repro it, can you file a ticket? Will fix ASAP.

@ghostdogpr 

> One thing I noticed was that because of System.exit(0) in RunnableSpec, the sbt session gets stopped when the test completes.

That's not good! I thought it set a trap to prevent that. 

I suppose we can block until the tests execute. That will throw an exception on Scala.js. Maybe we need separate versions for JVM and Scala.js?

**Comment by jdegoes** [comment] 2019-08-02 15:07
@adamgfraser 

> We should probably add a check for whether the predicate is equal to the subpredicate (i.e. it is a simple predicate with no subpredicates) and in that case only print a single line. I can take that issue and submit a PR on it.

Good idea. I also want to generalize `FailureDetails` to have a (non-empty) stack of predicate/values. Then each level can push its own one on the stack. Could also solve the problem.

**Comment by adamgfraser** [comment] 2019-08-02 15:57
@jdegoes That makes sense.

**Comment by edvmorango** [comment] 2019-08-02 16:06
@jdegoes @ghostdogpr I referenced the draft of my attempt. I will create a ticket.

**Comment by ghostdogpr** [comment] 2019-08-03 02:58
@jdegoes tested again with your latest changes and now the sbt session is not stopped 👍

**Comment by jdegoes** [comment] 2019-08-03 13:16
@ghostdogpr Awesome. We may have to support the exit behavior as a command-line option, so you could use ZIO Test from command-line without an SBT runner. But we can do that later.

**Comment by adamgfraser** [comment] 2021-08-22 21:21
We added an examples project so going to close this.

**Closed by adamgfraser** 2021-08-22 21:21 UTC
Labels: enhancement, good first issue, tests
