### ISSUE TITLE
Flaky ZStream Test

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#4278] opened 2020-10-05 18:51 UTC
```
[info] - ZStream JVM
[info]   - Constructors
[info]     - fromOutputStreamWriter
[info]       - is not affected by closing the output stream
[info] Timeout of 1 m exceeded.
```

https://app.circleci.com/pipelines/github/zio/zio/9149/workflows/2a360637-ff15-48ee-929e-f516f3808140/jobs/93193

**Comment by robmwalsh** [comment] 2020-10-06 02:03
duplicate of #4264

**Comment by adamgfraser** [comment] 2020-10-06 02:05
@robmwalsh Thank you! 🙏

**Closed** 2020-10-06 02:05 UTC
Labels: flaky tests, stream

**Comment by robmwalsh** [comment] 2020-10-06 02:14
@adamgfraser no problems - you may wish to add the labels to the other issue (I don't have permission)

**Comment by adamgfraser** [comment] 2020-10-06 02:22
@robmwalsh Done!
