### ISSUE TITLE
[Bug] Runtime#unsafeRunToFuture is broken in RC-18 

### ISSUE THREAD

**Issue by nktpro** [zio/zio#3013] opened 2020-03-04 07:06 UTC
`Runtime#unsafeRunToFuture` is broken in RC-18 release as part of interruption rework in https://github.com/zio/zio/commit/681063606b157b7f98f51c664fc7e7a4c1a82918. I did a full bisect of the recent commits and that one was confirmed to be the cause.

Here's a quick reproducer:

```
import java.time.{LocalDate, LocalDateTime}

import zio.clock.Clock
import zio.console.{Console, putStrLn}
import zio.duration._
import zio.{Schedule, Task, ZIO}

object BrokenUnsafeRunToFutureReproducer extends zio.App {
  override def run(args: List[String]): ZIO[zio.ZEnv, Nothing, Int] = {
    val effect = ZIO.effectSuspendTotal(putStrLn(s"Current time is ${LocalDateTime.now}"))
      .delay(1.second)

    val toFutureAndBackToEffect = for {
      rt <- ZIO.runtime[Console with Clock]
      _ <- Task.fromFuture { _ =>
        rt.unsafeRunToFuture(effect)
      }
    } yield ()

    toFutureAndBackToEffect
      .repeat(Schedule.fixed(1.second))
      .orDie
      .as(0)
  }
}
```

Which will terminate with:

```
Fiber failed.
An unchecked error was produced.
java.util.concurrent.ExecutionException: Boxed Exception
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.failure(Promise.scala:109)
	at scala.concurrent.Promise.failure$(Promise.scala:109)
	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:104)
	at zio.Fiber.$anonfun$toFutureWith$2(Fiber.scala:297)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:383)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:679)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException: Interrupted by fibers: #15
	at zio.Cause.$anonfun$squashWith$1(Cause.scala:348)
	at scala.Option.orElse(Option.scala:477)
	at zio.Cause.squashWith(Cause.scala:345)
	at zio.Cause.squashWith$(Cause.scala:343)
	at zio.Cause$Internal$Interrupt.squashWith(Cause.scala:648)
	at zio.Cause.squashWithTrace(Cause.scala:370)
	at zio.Cause.squashWithTrace$(Cause.scala:369)
	at zio.Cause$Internal$Interrupt.squashWithTrace(Cause.scala:648)
	... 6 more
Caused by: zio.Cause$FiberTrace: Fiber failed.
An interrupt was produced by #15.
No ZIO Trace available.
```

It's somewhat non-deterministic (hence the `repeat`).

**Comment by jdegoes** [comment] 2020-03-04 18:08
It looks like supervision is killing a fiber running the effect.

Why that is happening remains to be investigated, however. Probably the solution is a `forkDaemon` somewhere.

Thanks for the writeup, we will have this fixed in time for 1.0!

**Comment by adamgfraser** [comment] 2020-03-04 18:22
I looked into this a bit last night. I was able to resolve by using `forkDaemon` here:

```scala
  /**
   * Converts the effect into a [[scala.concurrent.Future]].
   */
  final def toFutureWith(f: E => Throwable): URIO[R, CancelableFuture[A]] =
    self.forkDaemon >>= (_.toFutureWith(f))
```

I think the issue is basically that the parent fiber can terminate before the child completes the promise in `Fiber.toFutureWith`. However, I noticed that when I did that interruption no longer interrupted the underlying effect (e.g. the same message continues to get printed to the console) so needs a little more work.

**Comment by jdegoes** [comment] 2020-03-05 00:51
I think it's time for `ZIO.adopt`. I can look into this over the weekend probably, or maybe Friday.

**Comment by octavz** [comment] 2020-03-06 09:33
@jdegoes  Hi, this is the only way to use `akka-http` with `ZIO`, and not only, any `unsafeToFuture` out there will crash.

There are a lot of people using this setup, please give this a high priority otherwise we have to stick to RC-17 and once this is fixed perhaps you can release a small update RC-18-xx.

Thank You

**Comment by jdegoes** [comment] 2020-03-06 12:15
I'll try to fix today!

**Comment by fsvehla** [comment] 2020-03-06 12:20
@octavz If it’s urgent, you could fulfill a `scala.concurrent.Promise` by using `unsafeRunAsync`, emulating `unsafeRunToFuture` (unless both methods share this issue)

**Comment by jdegoes** [comment] 2020-03-06 13:49
Anyone want to test #3040 to see if it solves the problem?

**Comment by senia-psm** [comment] 2020-03-06 16:18
@jdegoes I have ~10 tests that are broken with this bug. With #3040 all test are green! Thank you!

**Closed** 2020-03-06 20:34 UTC
Labels: bug
