### ISSUE TITLE
Potential Issue With Interaction Between ZLayer And Skunk

### ISSUE THREAD

**Issue by hossameldeen** [zio/zio#4777] opened 2021-03-09 03:16 UTC
## Description

Using a `ZManaged` gotten from a `ZLayer.fromManaged` causes `java.util.concurrent.RejectedExecutionException: Unable to run zio.internal.FiberContext`.

**Note:** The old issue description talked about a release-before-acquisition problem which I'd thought to be the root issue for the exception. However, after discussing below in the comments, there might not be such problem. Updated the description to reflect that the issue is the exception.

### Steps to reproduce

- Have a Postgres instance running on `http://localhost:5432` with username & password `postgres` and `postgres` (or change the config in the code below.
- Create a database called `zlayer-managed-early-released-reproduction-db` (or change the config in the code below).
- Run this file:
```scala
import zio._
import zio.interop.catz._
import skunk.codec.all._
import skunk._
import skunk.implicits._

object Main extends App {

  type ZSessionPool = Managed[Throwable, Session[Task]]

  def mkSessionPool(): Managed[Throwable, ZSessionPool] = {
    import natchez.Trace.Implicits.noop
    import zio.interop.catz._

    Session
      .pooled[Task](
        host = "localhost",
        port = 5432,
        user = "postgres",
        database = "zlayer-managed-early-released-reproduction-db",
        password = Some("postgres"),
        max = 10,
        strategy = Strategy.SearchPath
      )
      .toManagedZIO
      .map { resource =>
        resource.toManagedZIO
          .tapM(_ => UIO.succeed(println("Database session acquired")))
          .ensuring(UIO.succeed(println("Database session released")))
      }
  }

  val live: ZLayer[Any, Throwable, Has[ZSessionPool]] = {
    ZLayer.fromManaged(
      mkSessionPool()
    )
  }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val worksCorrectlyWithoutZLayer = (for {
      str <- mkSessionPool().use { sessionPool =>
        sessionPool.use { session =>
          session.prepare(sql"""SELECT 'abc'""".query(text)).use { pq =>
            pq.unique(Void)
          }
        }
      }
      _ <- Task.effect(println(s"Selected str=$str from the database"))
    } yield ()).exitCode

    val failsWithZLayer = (for {
      zSessionPool <-
        ZIO
          .access[Has[ZSessionPool]](_.get)
          .provideLayer(live)

      str <- zSessionPool.use { session =>
        session.prepare(sql"""SELECT 'abc'""".query(text)).use { pq =>
          pq.unique(Void)
        }
      }
      _ <- Task.effect(println(s"Selected str=$str from the database"))
    } yield ()).exitCode

    // Uncomment this and comment `failsWithZLayer` below and you'd find that it works
//    worksCorrectlyWithoutZLayer
    failsWithZLayer
  }
}
```

#### Expected result

To print:

```
Database session acquired
Database session released
Selected str=abc from the database
```

#### Actual result

Printed:

```
Database session released
Fiber failed.
An unchecked error was produced.
java.util.concurrent.RejectedExecutionException: Unable to run zio.internal.FiberContext$$Lambda$214/0x0000000800d50858@43c00a4a
	at zio.internal.FiberContext.evaluateLater(FiberContext.scala:778)
...
```

<details>

<summary>Click to show full log output</summary>

```
Database session released
Fiber failed.
An unchecked error was produced.
java.util.concurrent.RejectedExecutionException: Unable to run zio.internal.FiberContext$$Lambda$214/0x0000000800d50858@43c00a4a
	at zio.internal.FiberContext.evaluateLater(FiberContext.scala:778)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:539)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:778)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

Fiber:Id(1615259417927,1) was supposed to continue to:
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at fs2.io.tcp.SocketGroup.client(SocketGroup.scala:99)
  a future continuation at cats.effect.Resource$.liftF(Resource.scala:375)
  a future continuation at cats.effect.Resource.allocated_(Resource.scala:250)
  a future continuation at zio.ZIO.run(ZIO.scala:1640)
  a future continuation at zio.interop.CatsConcurrent.bracketCase(cats.scala:268)
  a future continuation at cats.ApplicativeError.onError(ApplicativeError.scala:196)
  a future continuation at cats.effect.Resource$.make(Resource.scala:342)
  a future continuation at cats.effect.Resource$.apply(Resource.scala:304)
  a future continuation at zio.interop.ZIOResourceSyntax$.toManagedZIO(catszmanaged.scala:50)
  a future continuation at zio.ZIO.run(ZIO.scala:1640)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged$.makeReserve(ZManaged.scala:1930)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:311)
  a future continuation at zio.ZManaged.mapM(ZManaged.scala:474)
  a future continuation at zio.ZManaged.onExit(ZManaged.scala:518)
  a future continuation at zio.ZIO.run(ZIO.scala:1640)
  a future continuation at zio.ZIO.run(ZIO.scala:1640)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged.onExit(ZManaged.scala:519)
  a future continuation at zio.ZIO.run(ZIO.scala:1640)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:256)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1026)
  a future continuation at zio.ZIO.run(ZIO.scala:1640)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1025)
  a future continuation at Main$.run(Main.scala:62)
  a future continuation at zio.ZIO.exitCode(ZIO.scala:543)

Fiber:Id(1615259417927,1) execution trace:
  at zio.internal.FiberContext.lock(FiberContext.scala:665)
  at zio.internal.FiberContext.lock(FiberContext.scala:665)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at cats.effect.Resource.allocated_(Resource.scala:233)
  at cats.effect.Resource.allocated_(Resource.scala:250)
  at cats.effect.Resource$.liftF(Resource.scala:375)
  at skunk.util.Namer$.apply(Namer.scala:19)
  at cats.effect.concurrent.Ref$.of(Ref.scala:179)
  at cats.FlatMap.flatten(FlatMap.scala:43)
  at cats.effect.concurrent.Ref$SyncRef.modify(Ref.scala:320)
  at skunk.util.Pool$.of(Pool.scala:85)
  at cats.effect.concurrent.Deferred$.apply(Deferred.scala:100)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZManaged$.makeReserve(ZManaged.scala:1927)
  at zio.ZManaged$.makeReserve(ZManaged.scala:1927)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4101)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZManaged.onExit(ZManaged.scala:518)
  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1297)
  at zio.ZRef$.make(ZRef.scala:749)
  at zio.ZManaged.onExit(ZManaged.scala:515)
  at zio.ZManaged.onExit(ZManaged.scala:515)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4101)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZIO.provideSome(ZIO.scala:1171)
  at zio.ZManaged.use(ZManaged.scala:1026)
  at zio.ZManaged$ReleaseMap$.make(ZManaged.scala:1297)
  at zio.ZRef$.make(ZRef.scala:749)
  at Main$.run(Main.scala:57)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at zio.ZIO$.bracketExit(ZIO.scala:2273)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at zio.ZManaged$ReleaseMap$$anon$1.releaseAll(ZManaged.scala:1332)
  at zio.ZIO$.foreach(ZIO.scala:2809)
  at zio.ZIO$.foreach(ZIO.scala:2808)
  at zio.ZIO.run(ZIO.scala:1640)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at zio.ZIO$.bracketExit(ZIO.scala:2273)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.ZIO.run(ZIO.scala:1640)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO.orDieWith(ZIO.scala:1048)
  at cats.effect.internals.BlockerPlatform.fromExecutorService(BlockerPlatform.scala:59)
  at cats.effect.internals.BlockerPlatform.fromExecutorService(BlockerPlatform.scala:53)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZIO.zipWith(ZIO.scala:2137)
  at zio.ZIO$.foreach(ZIO.scala:2808)
  at zio.ZIO.run(ZIO.scala:1640)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at zio.ZIO$.bracketExit(ZIO.scala:2273)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.ZIO.run(ZIO.scala:1640)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO.orDieWith(ZIO.scala:1048)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)
  at zio.ZIO.zipWith(ZIO.scala:2137)
  at zio.ZIO$.foreach(ZIO.scala:2808)
  at zio.ZIO.run(ZIO.scala:1640)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at zio.ZIO$.bracketExit(ZIO.scala:2273)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.ZIO.run(ZIO.scala:1640)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO.orDieWith(ZIO.scala:1048)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at zio.ZIO$.bracketExit(ZIO.scala:2273)
  at zio.internal.FiberContext.unlock(FiberContext.scala:668)
  at zio.internal.FiberContext.unlock(FiberContext.scala:668)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.ZIO.run(ZIO.scala:1640)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:161)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:154)
  at fs2.io.tcp.SocketGroup$.apply(SocketGroup.scala:407)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.lock(FiberContext.scala:665)
  at zio.internal.FiberContext.lock(FiberContext.scala:665)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2640)
  at zio.ZIO.bracket_(ZIO.scala:256)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:555)

Fiber:Id(1615259417927,1) was spawned by:

Fiber:Id(1615259417863,0) was supposed to continue to:
  a future continuation at zio.App.main(App.scala:57)
  a future continuation at zio.App.main(App.scala:56)

Fiber:Id(1615259417863,0) ZIO Execution trace: <empty trace>

Fiber:Id(1615259417863,0) was spawned by: <empty trace>
```

</details>

### Notes

- Not sure about the semantics of `ZLayer.fromManaged` -- in general, may not be that good at ZIO.
- As noted in the code, try commenting `failsWithZLayer` and uncommenting `worksCorrectlyWithoutZLayer` and you'll notice that it works correctly.
- You can find the reproduction repo [here](https://github.com/hossameldeen/zlayer-managed-early-released-reproduction), complete with the used libraries' versions, ... etc.

**Comment by hossameldeen** [comment] 2021-03-09 03:24
**Update:** Seems like the issue may not be just about `ZLayer`. I tried this code and it works successfully:

```scala
import zio._

object Main extends App {

  def mkManagedOfManaged(): Managed[Throwable, Managed[Throwable, Int]] = {
    ZManaged.succeed(
      ZManaged
        .succeed(7)
        .tapM(_ => UIO.succeed(println("Inner managed acquired")))
        .ensuring(UIO.succeed(println("Inner managed released")))
    )
  }

  val live: ZLayer[Any, Throwable, Has[Managed[Throwable, Int]]] = {
    ZLayer.fromManaged(
      mkManagedOfManaged()
    )
  }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val worksCorrectlyWithoutZLayer = (for {
      outerNum <- mkManagedOfManaged().use { managed =>
        managed.use { num =>
          Task.succeed(num)
        }
      }
      _ <- Task.effect(println(s"Managed of managed got $outerNum"))
    } yield ()).exitCode

    val failsWithZLayer = (for {
      managed <-
        ZIO
          .access[Has[Managed[Throwable, Int]]](_.get)
          .provideLayer(live)

      outerNum <- managed.use { num =>
        Task.succeed(num)
      }
      _ <- Task.effect(println(s"Managed of managed got $outerNum"))
    } yield ()).exitCode

    // Uncomment this and comment `failsWithZLayer` below and you'd find that it works
//    worksCorrectlyWithoutZLayer
    // UPDATE: It works in this example code
    failsWithZLayer
  }
}
```

**Comment by adamgfraser** [comment] 2021-03-09 03:26
@hossameldeen Thanks for reporting! Will take a look. If you are able to reproduce without a third party dependency that would help greatly.

**Comment by hossameldeen** [comment] 2021-03-09 03:38
@adamgfraser Thanks for the quick reply!

Actually, I was just going to post that it seems to work with `interop-cats` without the [skunk](https://github.com/tpolecat/skunk) stuff. Should I move this issue to skunk's repo instead?

The code that works with `interop-cats` without skunk:

```scala
import zio._
import cats.effect.Resource
import zio.interop.catz._

object Main extends App {

  def mkManagedOfManaged(): Managed[Throwable, Managed[Throwable, Int]] = {
    import zio.interop.catz._

    Resource
      .make[Task, Resource[Task, Int]](
        Task.succeed(Resource.make[Task, Int](Task.succeed(7))(_ => Task.unit))
      )(_ => Task.unit)
      .toManagedZIO
      .map { resource =>
        resource.toManagedZIO
          .tapM(_ => UIO.succeed(println("Inner managed acquired")))
          .ensuring(UIO.succeed(println("Inner managed released")))
      }
  }

  val live: ZLayer[Any, Throwable, Has[Managed[Throwable, Int]]] = {
    ZLayer.fromManaged(
      mkManagedOfManaged()
    )
  }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = {
    val worksCorrectlyWithoutZLayer = (for {
      outerNum <- mkManagedOfManaged().use { managed =>
        managed.use { num =>
          Task.succeed(num)
        }
      }
      _ <- Task.effect(println(s"Managed of managed got $outerNum"))
    } yield ()).exitCode

    val failsWithZLayer = (for {
      managed <-
        ZIO
          .access[Has[Managed[Throwable, Int]]](_.get)
          .provideLayer(live)

      outerNum <- managed.use { num =>
        Task.succeed(num)
      }
      _ <- Task.effect(println(s"Managed of managed got $outerNum"))
    } yield ()).exitCode

    // Uncomment this and comment `failsWithZLayer` below and you'd find that it works
//    worksCorrectlyWithoutZLayer
    // UPDATE: It works in this example code
    failsWithZLayer
  }
}
```

(P.S: Might have to go now. If you think this should be moved to skunk's repo, feel free to move it or close it here and I'll move it to skunk's repo when I'm available again)

**Comment by adamgfraser** [comment] 2021-03-09 04:10
I'm in no rush to close this until we get to the bottom of it but it does look less like it is a `ZLayer` finalizer issue.

One thing I noticed is this snippet from your original example:

```scala
      ZManaged
        .succeed(7)
        .tapM(_ => UIO.succeed(println("Inner managed acquired")))
        .ensuring(UIO.succeed(println("Inner managed released")))
```

This doesn't guarantee that `inner managed acquired` will execute before `inner managed released` because the `ensuring` is attached to the entire managed effect, so if the effect fails after it begins execution but before `inner managed acquired` is executed `inner managed released` will still be executed. I might also look at what you are trying to achieve with the inner and outer managed values that aren't composed together into a single managed since that is also an advanced use pattern that requires additional thought. Ideally this would be something more like `managed1 *> managed2`.

From the execution trace it seems as if there is some kind of failure in acquiring the database that then results in the release action being executed without acquire ever having been executed for reasons related to the above.

The `RejectedExecutedException` is also very suspicious and indicates that the `Executor` in the ZIO runtime is being overwhelmed with an extremely large number of `Runnable` values being submitted for execution which also makes me wonder if there is something else going on in your application or its interaction with the database.

**Comment by hossameldeen** [comment] 2021-03-09 12:55
> This doesn't guarantee that inner managed acquired will execute before inner managed released because the ensuring is attached to the entire managed effect, so if the effect fails after it begins execution but before inner managed acquired is executed inner managed released will still be executed.

I see.. Understood and agree.

My original problem is actually the `RejectedExecutionException` exception thrown; the point of release-before-acquire was just a debugging point. I'd thought release-before-acquire was the root indicator of the problem, but seems there may be no release-before-acquire issue in the first place -- just the thrown-exception problem.

> I might also look at what you are trying to achieve with the inner and outer managed values that aren't composed together into a single managed since that is also an advanced use pattern that requires additional thought.

My motivation for nested managed is for Skunk's `Session.pooled`, which returns a `Resource[F, Resource[F, Session[F]]]`. I create a `live` using `ZLayer.fromManaged` from outer `ZManaged`, which makes the inner `ZManaged` available for any service that needs to wire it.

So, _pseudo-code_ for typical usage would be:

```scala
import skunk.{Session, Strategy}
import zio.{Has, Managed, Task, ZLayer}

object ZSessionPoolClient {

  type ZSessionPool    = Managed[Throwable, Session[Task]]

  def mkSessionPool(): Managed[Throwable, ZSessionPool] = {
    import natchez.Trace.Implicits.noop
    import zio.interop.catz._

    Session
      .pooled[Task](
        host = "localhost",
        port = 5432,
        user = "postgres",
        database = "zlayer-managed-early-released-reproduction-db",
        password = Some("postgres"),
        max = 10,
        strategy = Strategy.SearchPath
      )
      .toManagedZIO
      .map { resource =>
        resource.toManagedZIO
          .tapM(_ => UIO.succeed(println("Database session acquired")))
          .ensuring(UIO.succeed(println("Database session released")))
      }
  }

  val live: ZLayer[Any, Throwable, Has[ZSessionPool]] = {
    ZLayer.fromManaged(
      mkSessionPool()
    )
  }
}
```

```scala
import zio._
import skunk._
import skunk.implicits._
import skunk.codec.all._
import skunk.data.Completion
import zio.interop.catz._

trait XyzRepository {
  def listXyzs(): Task[List[ListXyzsRepositoryOutput]]
}

object XyzRepository {

  class Live(zSessionPool: ZSessionPool)
      extends XyzRepository {

    override def listXyzs(): Task[List[ListXyzsRepositoryOutput]] = {
      zSessionPool.use { session =>
        session.prepare(SQL.selectAll).use { pq =>
          pq.stream(Void, 1024).compile.toList
        }
      }
    }

  object SQL {

    val selectAll: Query[Void, ListXyzsRepositoryOutput] =
      sql"""
           SELECT *
           FROM xyzs
       """
        .query(listXyzRepositoryOutput)
  }

  val live: ZLayer[Has[ZSessionPool], Nothing, Has[
    XyzRepository
  ]] =
    ZLayer.fromService(
      new Live(_)
    )
}
```

```scala
import zio._
import zio.interop.catz._

object Main extends App {

  val zSessionPoolClientLayer = ZSessionPoolClient.live

  val xyzRepositoryLayer = zSessionPoolClientLayer >>> XyzRepository.live

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = ???
}
```

Basically, the idea of of having any repository wire a `Resource[F, Session[F]]` (`SessionPool[F]`) which they can use to get a session. And since this `SessionPool[F]` is coming from `Session.pooled` which returns a `Resource[F, SessionPooled[F]]`, we use `ZLayer.fromManaged` to create the module providing the session pool, something like that.

(Note: Yes, perhaps I should acquire the session once per request, not in the repository layer .. and perhaps this code creates multiple session pools, one for each wiring, not sure. But anyway, this is irrelevant to this issue, I think. Just tried to give a context of why I have a Managed of Managed.)

> The RejectedExecutedException is also very suspicious and indicates that the Executor in the ZIO runtime is being overwhelmed with an extremely large number of Runnable values being submitted for execution which also makes me wonder if there is something else going on in your application or its interaction with the database.

Aha. I have no knowledge there, unfortunately, but the [repro repo](https://github.com/hossameldeen/zlayer-managed-early-released-reproduction) contains a full app that is ready to be run.

**Comment by adamgfraser** [comment] 2021-03-09 13:33
Okay, that makes sense regarding the two layers of managed values but I would use an operator like `Managed.make` for the inner `Managed`.

I'm happy to leave this open while you track down the source of the problem but at this point I'm not actively working on this from my end.

**Comment by hossameldeen** [comment] 2021-03-09 14:15
Updated the title with the updated knowledge that there's possibly no acquisition-before-release issue, and added a note on that in the description. If you this makes the issue confusing, I could reset the title, close this one, and open another one describing the issue as the exception.

**Comment by adamgfraser** [comment] 2021-03-09 14:23
I guess my question is are we able to replicate this without Skunk? If not I'm not really sure that there is an issue with ZIO or what we can do about it. If you're actively looking into this and we may have some follow up about some particular behavior in that library which exercises logic in ZIO that isn't otherwise exercised and leads to an unexpected result that is great. But if not I'm a little hesitant to have an issue here that is not actionable.

**Comment by hossameldeen** [comment] 2021-03-09 14:43
Makes sense.

No, I'm unable to replicate this without Skunk. However, does the fact that a version without a `ZLayer.fromManaged` works (the `worksCorrectlyWithoutZLayer` in the code above) while an equivalent version with `ZLayer.fromManaged` doesn't work (the `failsWithZLayer`) makes this a ZIO issue?

And I'm going to post this to Skunk's gitter in case anyone could help. If you think the point of `worksCorrectlyWithoutZLayer` doesn't make this a ZIO issue, we can close this issue in a few days if no one from Skunk has input.

**Comment by hossameldeen** [comment] 2021-03-09 16:42
Update: I don't think I have the permissions to label. I'd have labelled it: `bug`, `cats effect`, `zmanaged`, and a new label `interaction-with-3rd-party-lib`.

**Comment by adamgfraser** [comment] 2021-03-09 16:45
Yes. It works with one ZIO value and not another. It also works with every other resource except Skunk as far as we know. So I don't really think "not my problem" is an appropriate reaction. But nevertheless we will investigate it even if others are not.

**Comment by SirStoke** [comment] 2021-06-25 10:51
I don't know if this is useful to anyone, but I hit the same error and googling brought me here

Taking a look at the [repro](https://github.com/hossameldeen/zlayer-managed-early-released-reproduction/blob/master/src/main/scala/Main.scala) I think the reason `failsWithZLayer` fails is that `provideLayer` (correctly) disposes of the `Managed` after the execution:

```scala
    val failsWithZLayer = (for {
      zSessionPool <-
        ZIO
          .access[Has[ZSessionPool]](_.get)
          .provideLayer(live)
   
     // zSessionPool is already released here

      str <- zSessionPool.use { session =>
        session.prepare(sql"""SELECT 'abc'""".query(text)).use { pq =>
          pq.unique(Void)
        }
      }
```

This works:

```scala
    val failsWithZLayer = (for {
      zSessionPool <-
        ZIO
          .access[Has[ZSessionPool]](_.get)

      str <- zSessionPool.use { session =>
        session.prepare(sql"""SELECT 'abc'""".query(text)).use { pq =>
          pq.unique(Void)
        }
      }

      _ <- Task.effect(println(s"Selected str=$str from the database"))
    } yield ()).exitCode

    // Uncomment this and comment `failsWithZLayer` below and you'd find that it works
//    worksCorrectlyWithoutZLayer
    failsWithZLayer.provideCustomLayer(live).orDie
```

**Comment by adamgfraser** [comment] 2022-04-16 07:08
Going to close as I don't think this is actionable at this point.

**Closed by adamgfraser** 2022-04-16 07:08 UTC
