### ISSUE TITLE
Flaky tests causing CI failures

### ISSUE THREAD

**Issue by kyri-petrou** [zio/zio#9303] opened 2024-11-14 07:34 UTC
Following tests have been causing CI failures recently:

- CheckSpec / checkAllPar effect type is correctly inferred ([logs](https://github.com/zio/zio/actions/runs/11831467283/job/32966664135))
- ZStreamSpec / Combinators / mapZIOPar / parallelism is not exceeded ([logs](https://github.com/zio/zio/actions/runs/11815850244/job/32917903670))

We need to check whether the tests are flaky due to a flaky test implementation or a bug in the methods used by the tests

/cc @clarzte

**Comment by gipeshka** [comment] 2024-11-14 10:36
Hey guys. I think the issue is real. We have tests that check some ZIOStreams with mapZIOPar included. Since the upgrade to `2.1.12` those tests became flaky failing from time to time. Removing `mapZIOPar` from the stream seems to fix the issue.
The tests are marked as failed, but provide no error message whatsover.

**Comment by kyri-petrou** [comment] 2024-11-14 17:12
Wondering if this was caused by #9123. @regiskuckaertz any idea what might be causing this weird behaviour? (Both the test flakiness and how the test failure details disappear)

**Comment by regiskuckaertz** [comment] 2024-11-19 08:01
Apologies for the radio silence, I've stayed away from the computer for a few days. I mistakenly thought the child fibers would be closed before closing the stream even with the parent scope, i'm still not sure I fully understand what is happening.

**Closed as completed** 2024-11-19 10:17 UTC

**Comment by gergelyfabian** [comment] 2025-01-20 13:57
This caused issues in one of the repos where we depend on ZIO (in unit tests). Was introduced by 97d99b2b9b7e132361ef56f6ccc0b9654982e117 and fixed by 7375876bc0091fde6ad37c37418a25f051a16af9, found that with git bisecting over ZIO. This is just to confirm that #9123 was the cause.
