### ISSUE TITLE
Child fiber interrupted while parent runs onInterrupt

### ISSUE THREAD

**Issue by erikvanoosten** [zio/zio#8804] opened 2024-04-29 18:20 UTC
In zio-kafka we're trying to add clean shutdown. The goal is to complete processing a stream, that is, process it up to the end marker that we insert when interrupted. However, unfortunately the stream sometimes gets interrupted ahead of time as well.

Below is a minimizer. Every few executions the stream is interrupted, shown by the console output:
```
Stream end sent
Error joining fiber
stream interrupted, this should not happen
```

While we expect that the console output is always:
```
Stream end sent
Fiber joined
```

Our expectation is that the stream is not interrupted until after `fib.join.onInterrupt` completes.
In other words, we expect that child fibers are not interrupted as long as the parent is running `onInterrupt`.

If this is expected behavior, is there another way to achieve the same effect?

```scala
import zio.*
import zio.stream.*

object ZStreamInterrupt extends ZIOAppDefault {
  override val bootstrap = Runtime.removeDefaultLoggers ++ Runtime.addLogger(ZLogger.simple(println))

  private val shutdownTimeout = 5.seconds

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    val stream: ZStream[Any, Nothing, Take[Nothing, Long]] =
      ZStream
        .fromSchedule(Schedule.spaced(100.micros))
        .map(Take.single)

    val p = for {
      end <- Promise.make[Nothing, Unit]
      stoppableStream = stream.merge(ZStream.fromZIO(end.await).as(Take.end))
      fib <- stoppableStream
        .flattenTake
        .runDrain
        .onInterrupt(ZIO.logError("stream interrupted, this should not happen"))
        .forkScoped
      result <-
        fib.join.onInterrupt {
          end.succeed(()) *>
            ZIO.logError("Stream end sent") *>
            fib.join
              .timeout(shutdownTimeout)
              .tapErrorCause { cause =>
                ZIO.logErrorCause("Error joining fiber", cause)
              }
              .ignore *>
          ZIO.logError("Fiber joined")
        }
    } yield result

    // Interrupt after 1 second
    p.timeout(1.second)
  }
}
```

**Comment by erikvanoosten** [comment] 2024-04-29 19:05
Any of our attempt to minimize this further (not using stream) failed. In other words, it could be that this is a bug/feature of the streams implementation.

**Comment by jdegoes** [comment] 2024-04-30 14:41
In ZIO 2, transitive fiber interruption is "instantaneous". This means a great grand-child can be interrupted before a parent finishes its winddown process.

This is different behavior than earlier versions of ZIO. In general, it's a better default, but there are some cases where you might have to add explicit synchronization to prevent this behavior.

In this case, could be a bug in streams (or could be a feature, depending on your point of view). Interested in feedback.

**Comment by erikvanoosten** [comment] 2024-04-30 17:27
> where you might have to add explicit synchronization to prevent this behavior

A workaround would be great, but we're not sure how. We can't run the stream with `uninterruptable` because that causes other problems (the stream's finalizers are not run anymore).

> Interested in feedback.

My first thought was that since we're explicitly using `.onInterrupt` this could be a signal that child processes should not be interrupted yet. I am yet to find a serious idea where this would go wrong (something where inside the `.onInterrupt` we would wait for child fibers to be interrupted?), so perhaps this could be a good solution.

Another thought is that we could introduce an interrupt strategy that governs how child fibers are interrupted. For example, a zio might get method `.withChildFiberInterrupts(Boolean)`. When `false` is given, any fiber that is spawned while in the scope of that zio would not get interrupted when its parent gets interrupted.

**Comment by erikvanoosten** [comment] 2024-05-08 13:12
Interesting, under ZIO 2.1 (2.1.0-RC5) the problem does not seem to occur.

Does ZIO 2.1 not interrupt all fibers at once like ZIO 2.0 does?

**Comment by kyri-petrou** [comment] 2024-05-08 14:03
@erikvanoosten, would it be possible to test whether the issue is there with version 2.1-RC1? I changed a bunch of things after RC1 and want to know whether it's something I did or was done previously

**Comment by erikvanoosten** [comment] 2024-05-08 14:11
@kyri-petrou 2.1-RC1 also has the expected behavior.

BTW, I am testing this with the app listed above, but with the last line replaced by:
```scala
p.timeout(100.millis).repeatN(100000)
```

**Comment by eyalfa** [comment] 2024-07-15 08:52
@erikvanoosten this indeed looks strange (took me a while to get the point behind the test).
`fib` is bound to a scope, so it seems like the only way it can get an (external) interrupt is when the scope closes.
on the other side it seems the scope can't be closed before the `join` in the `onInterrupt` block is completed...
I'd try adding a finalizer on the scope logging the `Exit` causing the scope to close, perhaps this might reveal what's happening here

**Comment by svroonland** [comment] 2024-07-21 16:16
I'm going to try to further reduce this to the ZChannel level.

**Comment by erikvanoosten** [comment] 2024-07-25 18:22
@jdegoes it took some time but here is my reaction:

- Given a hierarchy of fibers, when a fiber is interrupted it makes most sense to interrupt bottom up. This is because child fibers may use some resource from their parent (the other way around would be rare). We need bottom-up because a clean-up action might need the resource that is managed by the fiber's parent. Similarly, a parent fiber can safely close a resource if it knows that all child-fibers are gone.
- We can imagine a recursive top-down tree walking algorithm for implementing the onInterrupt call backs: it starts at the fiber that is interrupted. First we apply the algorithm recursively on all child fibers in parallel, when those are complete, this is followed by calling onInterrupt on the given fiber.

Bonus variant:
- In rare cases a fiber may want to control the interrupts of its child fibers (maybe they need to be interrupted in a certain order). In these cases the fiber may set a runtime flag that allows it to receive the onInterrupt callback _before_ its children. When that onInterrupt completes, any left over child fibers are now interrupted in parallel.

The 'bonus variant' was conceived by mentally going through all the options, I do not actually know a use case but who knows! For zio-kafka it would not be needed.

**Comment by kyri-petrou** [comment] 2024-07-26 17:13
@erikvanoosten just to clarify, previously you mentioned this:

> Interesting, under ZIO 2.1 (2.1.0-RC5) the problem does not seem to occur.

Does the current version of ZIO (2.1.6) work as intended? Or is there something that still isn't working as you'd like it to be?

**Comment by erikvanoosten** [comment] 2024-07-26 17:29
> @erikvanoosten just to clarify, previously you mentioned this:
> 
> > Interesting, under ZIO 2.1 (2.1.0-RC5) the problem does not seem to occur.
> 
> Does the current version of ZIO (2.1.6) work as intended? Or is there something that still isn't working as you'd like it to be?

Thanks for your interest, but I am not sure what you are asking. Indeed, when I run the above reproducer a couple of thousand times it no longer fails with zio 2.1.6. But unfortunately, that the reproducer no longer reproduces does not mean much. If I apply the technique in zio-kafka the situation might be slightly different and unexpected behavior might arise again.

If at all possible, I would like to know how the system is _designed_ to behave and build on that instead.

**Comment by kyri-petrou** [comment] 2024-07-26 17:46
Ahh now I understand. So based on my understanding (which is good but not complete) is that interruption order depends on which variant of `fork` is used.

- `fork`: We issue interrupt signals to children prior to interrupting the parent, but there is no guarantee that the children will be interrupted before the parent is
- `forkScoped`: Interruption and release of resources is done in reverse order based on what's added to it
- `forkDaemon`: Children are not interrupted when the parent is

I believe that `forkScoped` should be providing the guarantees you need, but in case you need some more fine-tuned control of the child scope, you could perhaps explore forking the parent scope itself, and placing the child in it as follows:

```scala
  def forkInForkedScope[R, E, A](effect: => ZIO[R with Scope, E, A])(implicit
      trace: Trace
  ): ZIO[R with Scope, Nothing, Fiber.Runtime[E, A]] =
    ZIO.scope.flatMap(scope => scope.fork.flatMap(childScope => effect.forkIn(childScope)))
```

What this ensures is that anything that's added to the child's scope will be governed separately, while still linked to the parent's scope

**Comment by erikvanoosten** [comment] 2024-07-26 17:56
Thanks @kyri-petrou. That looks like something I can work with.

**Comment by kyri-petrou** [comment] 2024-07-26 18:37
No worries. I'll close it as completed for now but let me know if you come across any other issue related to this and I'll reopen it :)

**Closed as completed by kyri-petrou** 2024-07-26 18:37 UTC

**Comment by svroonland** [comment] 2024-11-12 20:19
This is the original issue for #9288.
