### ISSUE TITLE
Failure of ZIO tests ignored in Maven if using maven-surefire-plugin  

### ISSUE THREAD

**Issue by PhillHenry** [zio/zio#4092] opened 2020-08-13 15:01 UTC
I have a code base that mixes ZIO and plain Scala code. Because of this, my pom.xml had both _maven-surefire-plugin_ and _scalatest-maven-plugin_.  

I noticed there was a failing ZIO test but although Maven reported it as failing it did not abort the build.

Workaround:
1. Use just _scalatest-maven-plugin_ and remove _maven-surefire-plugin_ from your POM.
2. be sure to annotate your ZIO tests with @RunWith(classOf[ZTestJUnitRunner])
3. be sure that the class name of your ZIO tests end with "Test" while ScalaTest class names end with "Spec"

More information can be found in the README.md of https://github.com/PhillHenry/ZIO_Maven_TestFailures_Demo

**Comment by adamgfraser** [comment] 2020-08-13 18:35
@PhillHenry Thanks for reporting!

@dkarlinsky Would you be interested in taking a look at this one?

**Comment by dkarlinsky** [comment] 2020-08-13 18:36
@adamgfraser sure I'll take a look

**Comment by adamgfraser** [comment] 2020-08-13 19:09
@dkarlinsky Awesome!

**Comment by dkarlinsky** [comment] 2020-08-15 11:58
I did some debugging of zio-test-junit under surefire and it seems the issue is in the way surefire communicates events between the forked JVM actually running tests back to the maven JVM surefire itself is running in. 
The forked JVM where JUnit is running, prints JUnit events (such as "Test Failed") to stdout in surefire's special encoding. The problem is that this encoding doesn't deal well with empty strings (it prefers nulls) - so if any of the JUnit event fields surefire encodes, are empty string - it will fail to decode the even and discard it.
([here](https://github.com/apache/maven-surefire/blob/b0325d4b7142832696d22fea1ea654348a69c675/surefire-api/src/main/java/org/apache/maven/surefire/booter/ForkedChannelEncoder.java#L327)'s the encoder source)
This what seems to be happening the "Test Failed" event.
This seems to be fixed in version `3.0.0-M5` of surefire.
So, @PhillHenry, if you upgrade to this version you should be good.

On the other hand the empty string in our case was `message` - which actually shouldn't be empty, so this is probably a bug.
I'll keep investigating.

**Comment by PhillHenry** [comment] 2020-09-08 15:56
Cool. I updated to 3.0.0-M5 as you recommended and the issue went away.
Thanks, guys!

**Comment by adamgfraser** [comment] 2020-10-08 00:16
Resolved by #4286.

**Closed by adamgfraser** 2020-10-08 00:16 UTC
Labels: bug, help wanted, tests
