### ISSUE TITLE
Bug: ZIO.race not interrupting

### ISSUE THREAD

**Issue by tusharmath** [zio/zio#4553] opened 2021-01-13 06:35 UTC
**Code**
```scala
unsafeRunSync(ZIO.fail(1) race ZIO.never)
```

**Expected**
The program should return an `Exit.Failure(1)`

**Actual:**
The program continues to run indefinitely.

**Version:** `1.0.3`

**Comment by adamgfraser** [comment] 2021-01-13 23:13
I know there was some discussion on Discord about this but just to close the loop.

`race` not terminating here is expected behavior because race returns the first effect to succeed, waiting for the second effect if the first one fails. So in the example above after the left hand side fails it waits for a result from the right hand side, which never completes. I think this is relatively long standing behavior and there is an alternative operator `raceFirst` if you want the other semantics, so I don't think this is something that needs to be changed.

With regard to `raceFirst` at least in my local testing that does terminate, which is also expected behavior. It sounds like there may be some more specific issue on Ammonite regarding interaction between interrupting a process there and ZIO's interruption machinery, which we could definitely open an issue for.

@tusharmath Are you okay with closing this issue?

**Closed** 2021-01-14 02:03 UTC

**Comment by tusharmath** [comment] 2021-01-14 02:05
Thanks @adamgfraser! I will close this issue.
