### ISSUE TITLE
Stream lock up on merge/joinWith

### ISSUE THREAD

**Issue by artempyanykh** [zio/zio#466] opened 2018-12-16 20:45 UTC
Although specs are green the following code locks up in console (ran on commit 832d17a)

In case of `merge` it happens from time to time:
```
scala> val s1 = Stream.fromIterable(1.to(10000))
s1: scalaz.zio.stream.Stream[Nothing,Int] = scalaz.zio.stream.StreamPure$$anon$8@66f1c3b2

scala> unsafeRun(s1.merge(s1).foldLeft(0)(_+_))
res17: Int = 100010000

scala> unsafeRun(s1.merge(s1).foldLeft(0)(_+_))
res18: Int = 100010000

scala> unsafeRun(s1.merge(s1).foldLeft(0)(_+_))
res19: Int = 100010000

scala> unsafeRun(s1.merge(s1).foldLeft(0)(_+_))
res20: Int = 100010000

scala> unsafeRun(s1.merge(s1).foldLeft(0)(_+_))
res21: Int = 100010000

scala> unsafeRun(s1.merge(s1).foldLeft(0)(_+_))
// here it finally locked up
```

In case of joinWith it happens every time:
```
scala> val s1 = Stream.fromIterable(1.to(10000))
s1: scalaz.zio.stream.Stream[Nothing,Int] = scalaz.zio.stream.StreamPure$$anon$8@379cf31a

scala> unsafeRun(s1.joinWith[Nothing, Int, Int](s1)((x1, x2) => x1.flatMap(a => x1.map(b => a.orElse(b)))).foldLeft(0)(_ + _))
// in hanged here
```

Not sure what's going on -- I discovered it while trying to add Stream benchmarks that involve merging/joining to quantify the effect on GC pressure from this change https://github.com/scalaz/scalaz-zio/pull/465.

**Comment by hepin1989** [comment] 2018-12-16 20:54
Have you tested with groupby followed by mergeall ？Akka stream will stop there .

**Comment by RaasAhsan** [comment] 2018-12-17 20:22
There are some race conditions causing inconsistent causal orderings in `Queue` that are probably the reason for this. I've reported some via #460 and #447, which are being addressed in PRs #458 . However, I feel like I'm observing some additional ones past those, which I have yet to look into as well.

**Comment by ghostdogpr** [comment] 2018-12-18 00:00
I can reproduce the `joinWith` issue with just `Stream.fromIterable(1.to(2))`. The problem is that we call `take` twice concurrently. When one take reaches Take.End, the other `take` will never complete.

I guess that's why originally there was `queue.offer(Take.End).forever` in `toQueue`? Now that there is only one `Take.End`, the logic in `joinWith` doesn't really work. cc @RaasAhsan  @iravid 

I merged #458, @artempyanykh does it help with the random failures?

**Comment by RaasAhsan** [comment] 2018-12-18 01:10
Ah, that's right! I'm not in favor of reverting the `toQueue`, but I have a simple change in mind that'll fix `joinWith`.

**Comment by artempyanykh** [comment] 2018-12-19 09:16
`Stream.merge` doesn't lock up now, but I get `Interrupted` printed into stdout from time to time. Is it expected?

**Comment by ghostdogpr** [comment] 2018-12-22 01:15
@RaasAhsan @artempyanykh I stopped printing interruptions in https://github.com/scalaz/scalaz-zio/pull/478 (just merged)

**Closed** 2019-11-01 12:05 UTC
Labels: stream
