### ISSUE TITLE
ZIO vs Cats Effect implicits collision

### ISSUE THREAD

**Issue by tampler** [zio/zio#951] opened 2019-06-03 13:30 UTC
Hello 
Having a problem integrating ZIO 1.0-RC5 with http4s 0.21.0. 
I'm trying to add a JSON test [here](https://github.com/Clover-Group/zio_front/blob/5045426d7b5d97f253419d5ab19b86c59f166d6f/src/test/scala/http/JsonSpec.scala#L34), but get errors:
```bash
[error] /home/bku/work/clover/zio_front/src/test/scala/http/JsonSpec.scala:51:48: ambiguous implicit values:
[error]  both method monadErrorZManagedInstances in trait CatsZManagedInstances of type [R, E]=> cats.MonadError[[γ$1$]scalaz.zio.ZManaged[R,E,γ$1$],E]
[error]  and method taskConcurrentInstances in trait CatsInstances1 of type [R]=> cats.effect.Concurrent[[β$16$]scalaz.zio.ZIO[R,Throwable,β$16$]] with cats.SemigroupK[[β$17$]scalaz.zio.ZIO[R,Throwable,β$17$]]
[error]  match expected type cats.Applicative[F]
[error]  req <- request(Method.POST, "/").withBody(Ok(hello("world")))
```

Please help me to resolve this. 
Thank you!

**Comment by kaishh** [comment] 2019-06-03 16:46
Could you use explicit type parameters, e.g. `request[Task]`, `Ok[Task](_)` and see if that helps?

**Comment by tampler** [comment] 2019-06-04 10:12
@kaishh Thanks for your advice. That seemed to work, when I did this:
```scala
      req <- request[TodoTask](Method.POST, "/").withBody(Ok(hello("world")))
```
but now I get another error, which seems to be related to http4s. I'll debug this, but won't currently close the issue:
```bash
[error] ...: Cannot convert from cats.effect.IO[org.http4s.Response[cats.effect.IO]] 
to an Entity, because no EntityEncoder[[A]scalaz.zio.ZIO[clover.tsp.front.repository.Repository,
Throwable,A], cats.effect.IO[org.http4s.Response[cats.effect.IO]]] instance 
could be found.
[error] req <- request[TodoTask](Method.POST, "/").withBody(Ok(hello("world")))
```

**Comment by kaishh** [comment] 2019-06-04 11:09
@tampler `org.http4s.dsl.io._` is specialized to cats-effect IO. You need to instantiate a version for Task and remove that import.
```scala
val dsl = new Http4sDsl[Task] {}
import dsl._
```

**Comment by tampler** [comment] 2019-06-04 11:46
@kaishh Great advice, worked like a charm. I actually had similar code in my service .  This was authored by another guy.
Albeit not ZIO related, could you pls advice on the next implicit resolution error with http4s json:
Service.scala
```scala
  type TodoTask[A] = TaskR[R, A]
  implicit def circeJsonDecoder[A](implicit decoder: Decoder[A]): EntityDecoder[TodoTask, A] = jsonOf[TodoTask, A]
  implicit def circeJsonEncoder[A](implicit encoder: Encoder[A]): EntityEncoder[TodoTask, A] = jsonEncoderOf[TodoTask, A]
```
JsonSpec.scala
```scala
  val dsl: Http4sDsl[TodoTask] = Http4sDsl[TodoTask]
  import dsl._
  ...
  req <- request[TodoTask](Method.POST, "/").withEntity(Ok(hello("world")))
```
Results in the following implicit resolution error:
```bash
[error] ambiguous implicit values:
[error]  both method jsonEncoder in trait CirceInstances of type [F[_]](implicit evidence$9: cats.Applicative[F])org.http4s.EntityEncoder[F,io.circe.Json]
[error]  and method circeJsonEncoder in class Service of type [A](implicit encoder: io.circe.Encoder[A])org.http4s.EntityEncoder[clover.tsp.front.http.JsonSpec.todoService.TodoTask,A]
[error]  match expected type org.http4s.EntityEncoder[clover.tsp.front.http.JsonSpec.todoService.TodoTask,io.circe.Json]
[error]  req <- request[TodoTask](Method.POST, "/").withEntity(Ok(hello("world")))
```
Thank you for  a great help!
Boris

**Comment by kaishh** [comment] 2019-06-04 13:45
@tampler You need to stop importing `org,http4s.circe._`, because you already define a catch-all instance that conflicts with an implicit there. Note that the error message contains all information required to resolve. If you don't already do that, I highly recommend adopting a Scala IDE, such as Intellij or Metals - it can easily show you root causes of implicit problems right in-editor.

**Comment by tampler** [comment] 2019-06-04 13:56
Yeah, I'm using gvim

**Comment by kaishh** [comment] 2019-06-07 22:12
I'm closing if you have no more questions

**Closed by kaishh** 2019-06-07 22:12 UTC
Labels: bug, cats effect
